// This file was generated by vicinae codegen: do not edit manually.


interface JsonRpcMessage {
	jsonrpc: "2.0";
	method?: string;
	id?: number;
	params?: Record<string, any>;
	result?: any;
	error?: any;
}

interface ITransport {
	sendRequest(method: string, params: Record<string, any>): Promise<any>;
	sendNotification(method: string, params: Record<string, any>): void;
	onMessage(handler: (message: JsonRpcMessage) => void): void;
}

type Flavor = 'Strawberry' | 'Vanilla' | 'Orange' | 'Chocolate';

type Point = {
	x: string;
	y: string;
}

type Stats = {
	start: Point;
	end: Point;
}

type IceCream = {
	flavor: Flavor;
	price: string;
}

type AskResponse = {
	result: string;
}

class Maths {
	constructor(private readonly transport: ITransport) { }

	add(x: string, y: string): Promise<string[]> {
		return this.transport.sendRequest("Maths/add", { x, y });
	}

	mul(x: string, y: string): Promise<Point> {
		return this.transport.sendRequest("Maths/mul", { x, y });
	}

	distance(a: Point, b: Point): Promise<string> {
		return this.transport.sendRequest("Maths/distance", { a, b });
	}

	mulPoints(a: Point, b: Point): Promise<Point> {
		return this.transport.sendRequest("Maths/mulPoints", { a, b });
	}

}

class Beach {
	constructor(private readonly transport: ITransport) { }

	orderIceCream(flavor: Flavor): Promise<IceCream> {
		return this.transport.sendRequest("Beach/orderIceCream", { flavor });
	}

}

class Fucker {
	constructor(private readonly transport: ITransport) { }

	sayFuck(fuck: string, comment: string): Promise<string> {
		return this.transport.sendRequest("Fucker/sayFuck", { fuck, comment });
	}

}

class EventCore {
	constructor(private readonly transport: ITransport) { }

	handlerActivated(handler: (id: string) => void): void {
		this._handlers.handlerActivated.push(handler);

	}
	_handleEvent(type: string, params: Record<string, any>) {
		// some code in the future
	}
	private _handlers = {
		handlerActivated: [] as Array<(id: string) => void>,
	}
}

class UI {
	constructor(private readonly transport: ITransport) { }

	render(json: string): Promise<string> {
		return this.transport.sendRequest("UI/render", { json });
	}

}

class AI {
	constructor(private readonly transport: ITransport) { }

	ask(prompt: string): Promise<AskResponse> {
		return this.transport.sendRequest("AI/ask", { prompt });
	}

}

class ApiClipboard {
	constructor(private readonly transport: ITransport) { }

	readText(): Promise<string> {
		return this.transport.sendRequest("ApiClipboard/readText", {});
	}

	paste(text: string): Promise<string> {
		return this.transport.sendRequest("ApiClipboard/paste", { text });
	}

	clipboardChanged(handler: () => void): void {
		this._handlers.clipboardChanged.push(handler);

	}
	_handleEvent(type: string, params: Record<string, any>) {
		// some code in the future
	}
	private _handlers = {
		clipboardChanged: [] as Array<() => void>,
	}
}

class Client {
	constructor(private readonly transport: ITransport) {
		this.Maths = new Maths(this.transport);
		this.Beach = new Beach(this.transport);
		this.Fucker = new Fucker(this.transport);
		this.EventCore = new EventCore(this.transport);
		this.UI = new UI(this.transport);
		this.AI = new AI(this.transport);
		this.ApiClipboard = new ApiClipboard(this.transport);
		transport.onMessage(msg => {
			if (!msg.id && msg.method && msg.params) {
				const [service, event] = msg.method.split("/");
				if (service == 'EventCore') this.EventCore._handleEvent(event, msg.params);
				if (service == 'ApiClipboard') this.ApiClipboard._handleEvent(event, msg.params);
			}
		});
	}
	Maths: Maths;
	Beach: Beach;
	Fucker: Fucker;
	EventCore: EventCore;
	UI: UI;
	AI: AI;
	ApiClipboard: ApiClipboard;

}

const client = new Client({} as any);

const unsubscribe = client.EventCore.handlerActivated((id) => {
});

client.EventCore.handlerActivated((id: string) => {
});

unsubscribe();
