// This file was generated by vicinae codegen: do not edit manually.


interface JsonRpcMessage {
	jsonrpc: "2.0";
	method?: string;
	id?: number;
	params?: Record<string, any>;
	result?: any;
	error?: any;
}

interface ITransport {
	send(data: string): void;
}

type ToastStyle = 'Success' | 'Danger';

class ClientTransport {
	constructor(private readonly transport: ITransport) {
	}

	dispatchMessage(data: string) {
		const msg = JSON.parse(data) as JsonRpcMessage;

		if (msg.id) {
			const handler = this.requestMap.get(msg.id);

			if (handler) {
				if (msg.error) handler.reject();
				if (msg.params) handler.resolve(msg.params);
				this.requestMap.delete(msg.id);
			}
		}
		if (!msg.id && msg.method) {
			for (const cb of this.handlers.get(msg.method) ?? []) {
				cb(msg.params);
			}
		}
	}

	request<T>(method: string, params: Record<string, any>): Promise<T> {
		const id = this.id++;

		const p = new Promise<T>((resolve, reject) => {
			this.requestMap.set(id, { resolve: (msg) => resolve(msg as T), reject });
		});

		this.sendMessage({ jsonrpc: '2.0', id, method, params });

		return p;
	}

	subscribe(method: string, cb: (result: any) => void): void {
		this.handlers[method] = cb;
	}

	private sendMessage(msg: JsonRpcMessage) {
		this.transport.send(JSON.stringify(msg));
	}


	id = 0;
	requestMap = new Map<number, { resolve: (value: any) => void, reject: () => void }>;
	handlers = new Map<string, Array<(result: any) => void>>;
};

class EventCore {
	constructor(private readonly transport: ClientTransport) { }

	handlerActivated(handler: (id: string) => void): void {
		this.transport.subscribe('activated', (data) => handler(data.id));
	}
	_handleEvent(type: string, params: Record<string, any>) {
		// some code in the future
	}
	private _handlers = {
		handlerActivated: [] as Array<(id: string) => void>,
	}
}


class UI {
	constructor(private readonly transport: ClientTransport) { }

	render(json: string): Promise<void> {
		return this.transport.request({ id: 1, method: "UI / render", params: { json } });
	}

	showToast(style: ToastStyle, msg: string): Promise<string> {
		this.transport.send(JSON.stringify({ id: 1, method: "UI/showToast", params: { style, msg } }));
		const executor = (resolve, reject) => {
		};

		return new Promise(executor);
	}

	viewPushed(handler: (viewId: number) => void): void {
		this._handlers.viewPushed.push(handler);

	}
	_handleEvent(type: string, params: Record<string, any>) {
		// some code in the future
	}
	private _handlers = {
		viewPushed: [] as Array<(viewId: number) => void>,
	}

}




class Client {
	constructor(private readonly transport: ITransport) {
		this.ctransport = new ClientTransport(transport);
		this.EventCore = new EventCore(this.transport);
		this.UI = new UI(this.transport);
		transport.onMessage(msg => {
			if (!msg.id && msg.method && msg.params) {
				const [service, event] = msg.method.split("/");
				if (service == 'EventCore') this.EventCore._handleEvent(event, msg.params);
				if (service == 'UI') this.UI._handleEvent(event, msg.params);
			}
		});

		this.ctransport = {
		};
	}
	EventCore: EventCore;
	UI: UI;

	ctransport: ClientTransport;

}
