#include "../parser.hpp"
#include <sstream>
#include <ranges>

namespace {

inline std::string_view getTypename(const TypeValue &type) {
  if (auto ptr = std::get_if<TypeStruct *>(&type.data)) { return (*ptr)->name; }
  if (auto ptr = std::get_if<EnumValue>(&type.data)) { return ptr->name; }
  return "string";
}

inline std::string getTypeSignature(const TypeValue &type) {
  std::string str{getTypename(type)};
  if (type.isArray) str.append("[]");
  return str;
}

inline std::string generateType(const TypeStruct &s) {
  std::ostringstream oss;
  oss << "type " << s.name << " = {\n";

  for (const auto &field : s.fields) {
    oss << "\t" << field.name << ": " << getTypeSignature(field.type) << ";\n";
  }

  oss << "}";

  return oss.str();
}

inline std::string generateEnum(const EnumValue &e) {
  std::ostringstream oss;
  oss << "type " << e.name << " = ";

  for (const auto &[idx, value] : e.values | std::views::enumerate) {
    if (idx > 0) oss << " | ";
    oss << "'" << value << "'";
  }

  oss << ";";

  return oss.str();
}

inline std::string generateService(const Service &s) {
  std::ostringstream oss;
  oss << "interface " << s.name << " {\n";

  for (const auto &method : s.methods) {
    oss << "\t" << method.name << "(";

    for (const auto &[idx, param] : method.params | std::views::enumerate) {
      if (idx > 0) oss << ", ";
      oss << param.name << ": " << getTypeSignature(param.type);
    }

    oss << "): " << getTypeSignature(method.returnType) << ";\n";
  }

  oss << "}";

  return oss.str();
}

}; // namespace

inline std::string codegenTypescript(const Tree &tree) {
  std::ostringstream oss;

  oss << "// This file was generated by vicinae codegen: do not edit manually.\n\n";

  for (auto const &s : tree.enums) {
    oss << generateEnum(s) << "\n\n";
  }

  for (auto const &s : tree.structs) {
    oss << generateType(*s) << "\n\n";
  }

  for (auto const &s : tree.services) {
    oss << generateService(*s) << "\n\n";
  }

  return oss.str();
}
