#include "../parser.hpp"
#include <format>
#include <iomanip>
#include "codegen.hpp"
#include <sstream>
#include <ranges>

namespace {

inline std::string_view getTypename(const TypeValue &type) {
  if (auto ptr = std::get_if<TypeStruct *>(&type.data)) { return (*ptr)->name; }
  if (auto ptr = std::get_if<EnumValue>(&type.data)) { return ptr->name; }
  if (auto ptype = std::get_if<PrimitiveType>(&type.data)) {
    switch (*ptype) {
    case PrimitiveType::Void:
      return "void";
    case PrimitiveType::Boolean:
      return "boolean";
    case PrimitiveType::Number:
      return "number";
    case PrimitiveType::String:
      return "string";
    }
  }

  return "string";
}

inline std::string getTypeSignature(const TypeValue &type) {
  std::string str{getTypename(type)};
  if (type.isArray) str.append("[]");
  return str;
}

inline std::string generateType(const TypeStruct &s) {
  std::ostringstream oss;
  oss << "type " << s.name << " = {\n";

  for (const auto &field : s.fields) {
    oss << "\t" << field.name;

    if (field.type.isOptional) oss << "?";

    oss << ": " << getTypeSignature(field.type) << ";\n";
  }

  oss << "}";

  return oss.str();
}

inline std::string generateEnum(const EnumValue &e) {
  std::ostringstream oss;
  oss << "type " << e.name << " = ";

  for (const auto &[idx, value] : e.values | std::views::enumerate) {
    if (idx > 0) oss << " | ";
    oss << "'" << value << "'";
  }

  oss << ";";

  return oss.str();
}

inline std::string generateEventHandlerTypeSignature(const Event &event) {
  std::ostringstream oss;
  oss << "(";
  for (const auto &[idx, param] : event.params | std::views::enumerate) {
    if (idx > 0) oss << ", ";
    oss << param.name << ": " << getTypeSignature(param.type);
  }
  oss << ") => void";
  return oss.str();
}

inline std::string generateService(const Service &s) {
  std::ostringstream oss;
  oss << "class " << s.name << " {\n";

  oss << "\tconstructor(private readonly transport: ITransport) {}\n\n";

  for (const auto &method : s.methods) {
    oss << "\t" << method.name << "(";

    for (const auto &[idx, param] : method.params | std::views::enumerate) {
      if (idx > 0) oss << ", ";
      oss << param.name;
      if (param.type.isOptional) oss << "?";
      oss << ": " << getTypeSignature(param.type);
    }

    oss << "): " << "Promise<" << getTypeSignature(method.returnType) << "> {\n";

    std::string methodName = std::format("{}/{}", s.name, method.name);

    oss << "\t\treturn this.transport.sendRequest(" << std::quoted(methodName) << ", { ";

    for (const auto &[idx, param] : method.params | std::views::enumerate) {
      if (idx > 0) oss << ", ";
      oss << param.name;
    }

    oss << " }" << ");";
    oss << "\t" << "\n\t}\n\n";
  }

  if (!s.events.empty()) {
    for (const auto &event : s.events) {
      oss << "\t" << event.name << "(handler: " << generateEventHandlerTypeSignature(event) << "): void {\n";
      oss << "\t\tthis._handlers." << event.name << ".push(handler);\n";
      oss << "\n\t}\n";
    }

    oss << "\t_handleEvent(type: string, params: Record<string, any>) {\n";
    oss << "\t\t // some code in the future";
    oss << "\n\t}\n";

    oss << "\tprivate _handlers = {\n";
    for (const auto &event : s.events) {
      oss << "\t\t" << event.name << ": [] as Array<" << generateEventHandlerTypeSignature(event) << ">,\n";
    }
    oss << "\t}";
  }

  oss << "}";

  return oss.str();
}

}; // namespace

static constexpr const auto busCode = R"(
interface JsonRpcMessage {
	jsonrpc: "2.0";
	method?: string;
	id?: number;
	params?: Record<string, any>;
	result?: any;
	error?: any;
}

interface ITransport {
	sendRequest(method: string, params: Record<string, any>): Promise<any>;
	sendNotification(method: string, params: Record<string, any>): void;
	onMessage(handler: (message: JsonRpcMessage) => void): void;
}
)";

static std::string tab(int n) {
  std::string str;
  str.reserve(n);
  for (int i = 0; i != n; ++i)
    str += '\t';
  return str;
}

static std::string codegenTypescript(const Tree &tree) {
  std::ostringstream oss;

  oss << "// This file was generated by vicinae codegen: do not edit manually.\n\n";
  oss << busCode << "\n";

  for (auto const &s : tree.enums) {
    oss << generateEnum(s) << "\n\n";
  }

  for (auto const &s : tree.structs) {
    oss << generateType(*s) << "\n\n";
  }

  for (auto const &s : tree.services) {
    oss << generateService(*s) << "\n\n";
  }

  oss << "class Client {\n";
  oss << "\tconstructor(private readonly transport: ITransport) {\n";

  for (auto const &s : tree.services) {
    oss << "\t\tthis." << s->name << " = new " << s->name << "(this.transport);\n";
  }

  std::vector<std::string> serviceLines;

  serviceLines.reserve(tree.services.size());

  for (auto const &s : tree.services) {
    serviceLines.emplace_back(
        std::format(R"(if (service == '{}') this.{}.handleEvent(event, msg.params))", s->name, s->name));
  }

  oss << tab(2) << "transport.onMessage(msg => {\n";
  oss << tab(3) << "if (!msg.id && msg.method && msg.params) {\n";
  oss << tab(4) << "const [service, event] = msg.method.split(\"/\");\n";

  for (auto const &s : tree.services) {
    if (!s->events.empty()) {
      oss << tab(4) << "if (service == '" << s->name << "') this." << s->name
          << "._handleEvent(event, msg.params);"
          << "\n";
    }
  }

  oss << tab(3) << "}\n";
  oss << tab(2) << "});\n";
  oss << "\t}\n";

  for (auto const &s : tree.services) {
    oss << "\t" << s->name << ": " << s->name << ";\n";
  }

  oss << "\n}\n";

  return oss.str();
}

class TypeScriptCodeGenerator : public AbstractCodeGenerator {
  std::string name() const override { return "typescript"; }
  std::string generate(const Tree &ast) override { return codegenTypescript(ast); }
};
