
// generated by vicinae figura codegen - do not edit manually

interface JsonRpcMessage {
	jsonrpc: "2.0";
	method?: string;
	id?: number;
	params?: Record<string, any>;
	result?: any;
	error?: any;
}

interface ITransport {
	send(data: WireData): void;
}

export type WireData = Uint8Array;

const textEncoder = new TextEncoder();
const textDecoder = new TextDecoder();

class BeveWriter {
	private buf = new Uint8Array(4096);
	private view = new DataView(this.buf.buffer);
	private len = 0;

	value(v: unknown): void {
		if (v === null || v === undefined) {
			this.u8(0x00);
			return;
		}

		switch (typeof v) {
			case "boolean":
				this.u8(v ? 0x18 : 0x08);
				return;
			case "number":
				if (Number.isSafeInteger(v)) {
					this.u8(0x69);
					this.ensure(8);
					this.view.setBigInt64(this.len, BigInt(v), true);
					this.len += 8;
				} else {
					this.u8(0x61);
					this.ensure(8);
					this.view.setFloat64(this.len, v, true);
					this.len += 8;
				}
				return;
			case "string":
				this.u8(0x02);
				this.str(v);
				return;
			case "object":
				break;
			default:
				this.u8(0x00);
				return;
		}

		if (v instanceof Uint8Array) {
			this.u8(0x14);
			this.size(v.length);
			this.ensure(v.length);
			this.buf.set(v, this.len);
			this.len += v.length;
			return;
		}

		if (Array.isArray(v)) {
			this.u8(0x05);
			this.size(v.length);
			for (const item of v) {
				this.value(item === undefined || typeof item === "function" ? null : item);
			}
			return;
		}

		const asJson = (v as { toJSON?: unknown }).toJSON;
		if (typeof asJson === "function") {
			this.value(asJson.call(v));
			return;
		}

		const obj = v as Record<string, unknown>;
		const keys = Object.keys(obj).filter(
			(k) => obj[k] !== undefined && typeof obj[k] !== "function",
		);
		this.u8(0x03);
		this.size(keys.length);
		for (const key of keys) {
			this.str(key);
			this.value(obj[key]);
		}
	}

	finish(): Uint8Array {
		return this.buf.slice(0, this.len);
	}

	private ensure(extra: number) {
		if (this.len + extra <= this.buf.length) return;
		let capacity = this.buf.length * 2;
		while (capacity < this.len + extra) capacity *= 2;
		const next = new Uint8Array(capacity);
		next.set(this.buf.subarray(0, this.len));
		this.buf = next;
		this.view = new DataView(next.buffer);
	}

	private u8(v: number) {
		this.ensure(1);
		this.buf[this.len++] = v;
	}

	private size(v: number) {
		if (v < 64) {
			this.u8(v << 2);
		} else if (v < 16384) {
			this.ensure(2);
			this.view.setUint16(this.len, (v << 2) | 1, true);
			this.len += 2;
		} else if (v < 1073741824) {
			this.ensure(4);
			this.view.setUint32(this.len, ((v << 2) | 2) >>> 0, true);
			this.len += 4;
		} else {
			this.ensure(8);
			this.view.setBigUint64(this.len, (BigInt(v) << 2n) | 3n, true);
			this.len += 8;
		}
	}

	private str(s: string) {
		const bytes = textEncoder.encode(s);
		this.size(bytes.length);
		this.ensure(bytes.length);
		this.buf.set(bytes, this.len);
		this.len += bytes.length;
	}
}

class BeveReader {
	private view: DataView;
	private pos = 0;

	constructor(private readonly buf: Uint8Array) {
		this.view = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
	}

	value(): any {
		const tag = this.buf[this.pos];

		switch (tag & 7) {
			case 0: {
				this.pos++;
				if (tag === 0x00) return null;
				return (tag & 0x10) !== 0;
			}
			case 1: {
				this.pos++;
				return this.number(tag);
			}
			case 2: {
				this.pos++;
				return this.str();
			}
			case 3: {
				this.pos++;
				if (((tag >> 3) & 3) !== 0) {
					throw new Error("BEVE: only string-keyed objects are supported");
				}
				const count = this.size();
				const obj: Record<string, any> = {};
				for (let i = 0; i < count; i++) {
					const key = this.str();
					const value = this.value();
					if (key === "__proto__") {
						Object.defineProperty(obj, key, {
							value,
							enumerable: true,
							configurable: true,
							writable: true,
						});
					} else {
						obj[key] = value;
					}
				}
				return obj;
			}
			case 4: {
				this.pos++;
				return this.typedArray(tag);
			}
			case 5: {
				this.pos++;
				const count = this.size();
				const arr = new Array(count);
				for (let i = 0; i < count; i++) arr[i] = this.value();
				return arr;
			}
			default:
				throw new Error(`BEVE: unsupported tag 0x${tag.toString(16)}`);
		}
	}

	private number(tag: number): number {
		const kind = (tag >> 3) & 3;
		const width = 1 << ((tag >> 5) & 7);
		const at = this.pos;
		this.pos += width;

		if (kind === 0) {
			if (width === 4) return this.view.getFloat32(at, true);
			if (width === 8) return this.view.getFloat64(at, true);
			throw new Error(`BEVE: unsupported float width ${width}`);
		}

		if (kind === 1) {
			if (width === 1) return this.view.getInt8(at);
			if (width === 2) return this.view.getInt16(at, true);
			if (width === 4) return this.view.getInt32(at, true);
			if (width === 8) return Number(this.view.getBigInt64(at, true));
		} else {
			if (width === 1) return this.view.getUint8(at);
			if (width === 2) return this.view.getUint16(at, true);
			if (width === 4) return this.view.getUint32(at, true);
			if (width === 8) return Number(this.view.getBigUint64(at, true));
		}

		throw new Error(`BEVE: unsupported integer width ${width}`);
	}

	private typedArray(tag: number): any {
		const kind = (tag >> 3) & 3;
		const exponent = (tag >> 5) & 7;
		const count = this.size();

		if (kind === 3) {
			if (exponent === 1) {
				const arr = new Array(count);
				for (let i = 0; i < count; i++) arr[i] = this.str();
				return arr;
			}
			const arr = new Array(count);
			for (let i = 0; i < count; i++) {
				const byte = this.buf[this.pos + (i >> 3)];
				arr[i] = (byte & (1 << (i & 7))) !== 0;
			}
			this.pos += (count + 7) >> 3;
			return arr;
		}

		const width = 1 << exponent;

		if (kind === 2 && width === 1) {
			const bytes = this.buf.slice(this.pos, this.pos + count);
			this.pos += count;
			return bytes;
		}

		const arr = new Array(count);
		for (let i = 0; i < count; i++) {
			const numberTag = (exponent << 5) | (kind << 3) | 1;
			arr[i] = this.number(numberTag);
		}
		return arr;
	}

	private size(): number {
		const config = this.buf[this.pos] & 3;
		if (config === 0) return this.buf[this.pos++] >> 2;
		if (config === 1) {
			const v = this.view.getUint16(this.pos, true) >> 2;
			this.pos += 2;
			return v;
		}
		if (config === 2) {
			const v = this.view.getUint32(this.pos, true) >>> 2;
			this.pos += 4;
			return v;
		}
		const v = this.view.getBigUint64(this.pos, true) >> 2n;
		this.pos += 8;
		return Number(v);
	}

	private str(): string {
		const n = this.size();
		const s = textDecoder.decode(this.buf.subarray(this.pos, this.pos + n));
		this.pos += n;
		return s;
	}
}

function encodeMessage(msg: JsonRpcMessage): WireData {
	const writer = new BeveWriter();
	writer.value(msg);
	return writer.finish();
}

function decodeMessage(data: WireData): JsonRpcMessage {
	return new BeveReader(data).value() as JsonRpcMessage;
}

type EventSubscription = {
	unsubscribe: () => void;
};

export class RpcTransport {
	constructor(private readonly transport: ITransport) { }

	dispatchMessage(data: WireData) {
		const msg = decodeMessage(data);

		if (msg.id !== undefined) {
			const handler = this.requestMap.get(msg.id);

			if (handler) {
				if (msg.error) handler.reject(msg.error);
				else handler.resolve(msg.result);
				this.requestMap.delete(msg.id);
			}
		}
		if (msg.id === undefined && msg.method) {
			for (const cb of this.handlers.get(msg.method) ?? []) {
				cb(msg.params);
			}
		}
	}

	request<T>(method: string, params: Record<string, any>): Promise<T> {
		const id = this.id++;
		const promise = new Promise<T>((resolve, reject) => {
			this.requestMap.set(id, { resolve: (msg) => resolve(msg as T), reject });
		});

		this.sendMessage({ jsonrpc: '2.0', id, method, params });

		return promise;
	}

	subscribe(method: string, cb: (result: any) => void): EventSubscription {
		const handlers = this.handlers.get(method);

		if (handlers) handlers.push(cb);
		else this.handlers.set(method, [cb]);

		return {
			unsubscribe: () => {
				const handlers = this.handlers.get(method);

				if (handlers) {
					handlers.splice(handlers.indexOf(cb), 1);
				}
			},
		};
	}

	private sendMessage(msg: JsonRpcMessage) {
		this.transport.send(encodeMessage(msg));
	}


	private id = 1;
	private requestMap = new Map<number, { resolve: (value: any) => void, reject: (error: any) => void }>;
	private handlers = new Map<string, Array<(result: any) => void>>;
};

export type ImageMask = 'None' | 'Circle' | 'RoundedRectangle';

export type ToastStyle = 'Success' | 'Info' | 'Warning' | 'Error' | 'Dynamic';

export type PopToRootType = 'Default' | 'Immediate' | 'Suspended';

export type ConfirmAlertActionStyle = 'Default' | 'Destructive' | 'Cancel';

export type NotificationUrgency = 'Low' | 'Normal' | 'High';

export type FileSearchCategory = 'Other' | 'Directory' | 'Image' | 'Video' | 'Audio' | 'Document' | 'Archive' | 'Application';

export type LaunchType = 'User' | 'Background' | 'CommandLine';

export type WallpaperFit = 'Cover' | 'Contain' | 'Stretch' | 'Center' | 'Tile';

export type Application = {
	id: string;
	name: string;
	icon?: string;
	path: string;
}

export type RunInTerminalPayload = {
	cmdline: string[];
	hold: boolean;
	appId?: string;
	workingDirectory?: string;
	title?: string;
}

export type ThemedImageSource = {
	light?: string;
	dark?: string;
}

export type ImageSource = {
	raw?: string;
	themed?: ThemedImageSource;
}

export type DynamicColor = {
	light: string;
	dark: string;
	adjustContrast?: boolean;
}

export type ColorLike = {
	raw?: string;
	dynamic?: DynamicColor;
}

export type Image = {
	source?: ImageSource;
	fallback?: ImageSource;
	mask?: ImageMask;
	tintColor?: ColorLike;
	fileIcon?: string;
}

export type ConfirmAlertAction = {
	title: string;
	style: ConfirmAlertActionStyle;
}

export type ConfirmAlertPayload = {
	title: string;
	description: string;
	primaryAction: ConfirmAlertAction;
	dismissAction: ConfirmAlertAction;
	rememberUserChoice: boolean;
	icon?: Image;
}

export type DesktopNotificationPayload = {
	title: string;
	body: string;
	icon?: Image;
	urgency: NotificationUrgency;
}

export type Rect = {
	x: number;
	y: number;
	width: number;
	height: number;
}

export type Size = {
	width: number;
	height: number;
}

export type Window = {
	id: string;
	title: string;
	workspaceId: string;
	active: boolean;
	fullscreen: boolean;
	bounds: Rect;
	app?: Application;
}

export type Screen = {
	name: string;
	model: string;
	make: string;
	serial?: string;
	bounds: Rect;
	physicalResolution: Size;
	active: boolean;
}

export type Workspace = {
	id: string;
	name: string;
	active: boolean;
	fullscreen: boolean;
	monitor?: string;
}

export type ClipboardContent = {
	text?: string;
	html?: string;
	urls?: string[];
}

export type ClipboardOptions = {
	concealed: boolean;
}

export type FileInfo = {
	path: string;
	category: FileSearchCategory;
	mimeType?: string;
}

export type FileSearchFilters = {
	category?: FileSearchCategory;
}

export type FileSearchOptions = {
	filters: FileSearchFilters;
	limit: number;
}

export type UpdateCommandMetadataPayload = {
	subtitle?: string;
}

export type LaunchCommandOptions = {
	extensionName: string;
	name: string;
	ownerOrAuthorName: string;
	type: LaunchType;
	arguments?: any;
	context?: any;
	fallbackText?: string;
}

export type PKCEClientOptions = {
	name: string;
	id?: string;
	description: string;
	icon?: Image;
}

export type AuthorizeRequest = {
	client: PKCEClientOptions;
	url: string;
}

export type AuthorizeResponse = {
	code: string;
}

export type TokenSet = {
	accessToken: string;
	refreshToken?: string;
	idToken?: string;
	expiresIn?: number;
	scope?: string;
	updatedAt: number;
}

export type SetTokensRequest = {
	providerId?: string;
	accessToken: string;
	refreshToken?: string;
	idToken?: string;
	expiresIn?: number;
	scope?: string;
}

export type TokenSetResponse = {
	set?: TokenSet;
}

export type SetWallpaperOptions = {
	fit?: WallpaperFit;
	screen?: string;
}

export type BrowserTab = {
	id: number;
	title?: string;
	url: string;
	active: boolean;
	browserId: string;
}

class ApplicationService {
	constructor(private readonly transport: RpcTransport) {}

	list(target?: string): Promise<Application[]> {
		return this.transport.request("Application/list", { target});	
	}

	open(target: string, appId?: string): Promise<void> {
		return this.transport.request("Application/open", { target, appId});	
	}

	getDefault(target: string): Promise<Application> {
		return this.transport.request("Application/getDefault", { target});	
	}

	showInFileBrowser(target: string, select: boolean): Promise<void> {
		return this.transport.request("Application/showInFileBrowser", { target, select});	
	}

	runInTerminal(opts: RunInTerminalPayload): Promise<boolean> {
		return this.transport.request("Application/runInTerminal", { opts});	
	}

}

class UIService {
	constructor(private readonly transport: RpcTransport) {}

	render(json: Uint8Array): Promise<void> {
		return this.transport.request("UI/render", { json});	
	}

	showToast(id: string, title: string, message: string, style: ToastStyle): Promise<void> {
		return this.transport.request("UI/showToast", { id, title, message, style});	
	}

	updateToast(id: string, title: string): Promise<void> {
		return this.transport.request("UI/updateToast", { id, title});	
	}

	hideToast(id: string): Promise<void> {
		return this.transport.request("UI/hideToast", { id});	
	}

	showHud(text: string, clear_root: boolean, popToRoot: PopToRootType): Promise<void> {
		return this.transport.request("UI/showHud", { text, clear_root, popToRoot});	
	}

	closeMainWindow(clearRoot: boolean, popToRoot: PopToRootType): Promise<void> {
		return this.transport.request("UI/closeMainWindow", { clearRoot, popToRoot});	
	}

	popToRoot(clearSearchBar: boolean): Promise<void> {
		return this.transport.request("UI/popToRoot", { clearSearchBar});	
	}

	confirmAlert(payload: ConfirmAlertPayload): Promise<boolean> {
		return this.transport.request("UI/confirmAlert", { payload});	
	}

	pushView(): Promise<void> {
		return this.transport.request("UI/pushView", { });	
	}

	popView(): Promise<void> {
		return this.transport.request("UI/popView", { });	
	}

	setSearchText(text: string): Promise<void> {
		return this.transport.request("UI/setSearchText", { text});	
	}

	getSelectedText(): Promise<string> {
		return this.transport.request("UI/getSelectedText", { });	
	}

	sendDesktopNotification(data: DesktopNotificationPayload): Promise<void> {
		return this.transport.request("UI/sendDesktopNotification", { data});	
	}

	viewPoped(handler: () => void): EventSubscription {
		return this.transport.subscribe("UI/viewPoped", (msg) => handler())
	}
	viewPushed(handler: () => void): EventSubscription {
		return this.transport.subscribe("UI/viewPushed", (msg) => handler())
	}
}

class WindowManagementService {
	constructor(private readonly transport: RpcTransport) {}

	focusWindow(winId: string): Promise<boolean> {
		return this.transport.request("WindowManagement/focusWindow", { winId});	
	}

	getActiveWindow(): Promise<Window> {
		return this.transport.request("WindowManagement/getActiveWindow", { });	
	}

	getActiveWorkspace(): Promise<Workspace> {
		return this.transport.request("WindowManagement/getActiveWorkspace", { });	
	}

	getWindows(workspaceId?: string): Promise<Window[]> {
		return this.transport.request("WindowManagement/getWindows", { workspaceId});	
	}

	getScreens(): Promise<Screen[]> {
		return this.transport.request("WindowManagement/getScreens", { });	
	}

	getWorkspaces(): Promise<Workspace[]> {
		return this.transport.request("WindowManagement/getWorkspaces", { });	
	}

	setWindowBounds(winId: string, bounds: Rect): Promise<void> {
		return this.transport.request("WindowManagement/setWindowBounds", { winId, bounds});	
	}

}

class ClipboardService {
	constructor(private readonly transport: RpcTransport) {}

	copy(content: ClipboardContent, options: ClipboardOptions): Promise<void> {
		return this.transport.request("Clipboard/copy", { content, options});	
	}

	paste(content: ClipboardContent): Promise<void> {
		return this.transport.request("Clipboard/paste", { content});	
	}

	clear(): Promise<void> {
		return this.transport.request("Clipboard/clear", { });	
	}

	readContent(): Promise<ClipboardContent> {
		return this.transport.request("Clipboard/readContent", { });	
	}

}

class StorageService {
	constructor(private readonly transport: RpcTransport) {}

	get(key: string): Promise<any> {
		return this.transport.request("Storage/get", { key});	
	}

	set(key: string, value: any): Promise<void> {
		return this.transport.request("Storage/set", { key, value});	
	}

	remove(key: string): Promise<void> {
		return this.transport.request("Storage/remove", { key});	
	}

	clear(): Promise<void> {
		return this.transport.request("Storage/clear", { });	
	}

	list(): Promise<any> {
		return this.transport.request("Storage/list", { });	
	}

}

class FileSearchService {
	constructor(private readonly transport: RpcTransport) {}

	search(q: string, opts: FileSearchOptions): Promise<FileInfo[]> {
		return this.transport.request("FileSearch/search", { q, opts});	
	}

}

class CommandService {
	constructor(private readonly transport: RpcTransport) {}

	launchCommand(options: LaunchCommandOptions): Promise<void> {
		return this.transport.request("Command/launchCommand", { options});	
	}

	updateCommandMetadata(payload: UpdateCommandMetadataPayload): Promise<void> {
		return this.transport.request("Command/updateCommandMetadata", { payload});	
	}

	openExtensionPreferences(): Promise<void> {
		return this.transport.request("Command/openExtensionPreferences", { });	
	}

	openCommandPreferences(): Promise<void> {
		return this.transport.request("Command/openCommandPreferences", { });	
	}

}

class OAuthService {
	constructor(private readonly transport: RpcTransport) {}

	authorize(payload: AuthorizeRequest): Promise<AuthorizeResponse> {
		return this.transport.request("OAuth/authorize", { payload});	
	}

	getTokens(id?: string): Promise<TokenSetResponse> {
		return this.transport.request("OAuth/getTokens", { id});	
	}

	setTokens(payload: SetTokensRequest): Promise<void> {
		return this.transport.request("OAuth/setTokens", { payload});	
	}

	removeTokens(id?: string): Promise<void> {
		return this.transport.request("OAuth/removeTokens", { id});	
	}

}

class WallpaperService {
	constructor(private readonly transport: RpcTransport) {}

	set(path: string, options: SetWallpaperOptions): Promise<void> {
		return this.transport.request("Wallpaper/set", { path, options});	
	}

}

class BrowserExtensionService {
	constructor(private readonly transport: RpcTransport) {}

	getTabs(): Promise<BrowserTab[]> {
		return this.transport.request("BrowserExtension/getTabs", { });	
	}

	focusTab(browserId: string, tabId: number): Promise<void> {
		return this.transport.request("BrowserExtension/focusTab", { browserId, tabId});	
	}

}

class EventCoreService {
	constructor(private readonly transport: RpcTransport) {}

	handlerActivated(handler: (id: string, args: any[]) => void): EventSubscription {
		return this.transport.subscribe("EventCore/handlerActivated", (msg) => handler(msg.id, msg.args))
	}
}

export class Client {
	constructor(private readonly transport: RpcTransport) {
		this.Application = new ApplicationService(this.transport);
		this.UI = new UIService(this.transport);
		this.WindowManagement = new WindowManagementService(this.transport);
		this.Clipboard = new ClipboardService(this.transport);
		this.Storage = new StorageService(this.transport);
		this.FileSearch = new FileSearchService(this.transport);
		this.Command = new CommandService(this.transport);
		this.OAuth = new OAuthService(this.transport);
		this.Wallpaper = new WallpaperService(this.transport);
		this.BrowserExtension = new BrowserExtensionService(this.transport);
		this.EventCore = new EventCoreService(this.transport);
	}

  	route(msg: WireData): void { this.transport.dispatchMessage(msg); }
  	Application: ApplicationService;
	UI: UIService;
	WindowManagement: WindowManagementService;
	Clipboard: ClipboardService;
	Storage: StorageService;
	FileSearch: FileSearchService;
	Command: CommandService;
	OAuth: OAuthService;
	Wallpaper: WallpaperService;
	BrowserExtension: BrowserExtensionService;
	EventCore: EventCoreService;

}
