[meta]
version = 1
name = "Vicinae Dark"
description = "Default Vicinae dark palette"
variant = "dark"
inherits = ""

[colors.core]
accent = "#2f6fed"
accent_foreground = "#ffffff"
background = "#1a1a1a"
foreground = "#e8e6e1"
secondary_background = "#242424"
border = "#2e2e2e"

[colors.main_window]
border = "#2e2e2e"

[colors.settings_window]
border = "#2e2e2e"

[colors.accents]
blue = "#2f6fed"
green = "#3a9c61"
magenta = "#bc8cff"
orange = "#f0883e"
red = "#b9543b"
yellow = "#bfae78"
cyan = "#18a5b3"
purple = "#bc8cff"

[colors.text]
default = "#e8e6e1"
muted = "#e8e6e1"
danger = "#b9543b"
success = "#3a9c61"

[colors.text.links]
default = "#2f6fed"
visited = "#bc8cff"

[colors.text.selection]
background = "#2f6fed"
foreground = "#ffffff"

[colors.input]
border = "#2e2e2e"
border_focus = "#2f6fed"
border_error = "#b9543b"
placeholder = "#e8e6e1"

[colors.button.primary]
background = "#2e2e2e"
foreground = "#e8e6e1"

[colors.button.primary.hover]
background = "#2e2e2e"
foreground = "#2e2e2e"

[colors.list.item.hover]
background = "#2e2e2e"
foreground = "#e8e6e1"

[colors.list.item.selection]
background = "#2e2e2e"
foreground = "#e8e6e1"
secondary_background = "#2e2e2e"
secondary_foreground = "#e8e6e1"

[colors.grid.item.selection]
outline = "#e8e6e1"

[colors.grid.item.hover]
outline = "#e8e6e1"

[colors.grid.item]
background = "#242424"

[colors.scrollbars]
background = "#2e2e2e"
secondary_background = "#2e2e2e"

[colors.tooltip]
background = "#242424"
foreground = "#e8e6e1"
border = "#2e2e2e"

[colors.loading]
bar = "#e8e6e1"
spinner = "#e8e6e1"

