# Example vicinae v0.15.0+ theme format
# This theme file only affects the color that are used to theme Vicinae.
# Font size and window opacity are configured inside Vicinae directly, independently
# from the current theme.

# colors can be expressed as hex:
# base01 = "#FFFFFF"
# short hex:
# base01 = "#FFF"
# and optionally specify an opacity:
# base01 = { color = "#FFF", opacity = 0.8 }

[meta]
version = "1"
name = "My Theme"
description = "This is a wonderful theme"
variant = "dark"
#icon = "./icon.png" # optional: path is relative to the directory the theme is found in

# ------------------------------------------------------------------------------
# Core / Accent colors
# ------------------------------------------------------------------------------
[colors.core]
accent = "<color>"             # general accent color (selection, focus)
accent_foreground = "<color>"  # foreground on accent backgrounds
foreground = "<color>"         # main text/icon color

# ------------------------------------------------------------------------------
# Base Palette
# ------------------------------------------------------------------------------
[colors.accents]
blue = "<color>"
green = "<color>"
magenta = "<color>"
orange = "<color>"
red = "<color>"
yellow = "<color>"
cyan = "<color>"
purple = "<color>"

# ------------------------------------------------------------------------------
# Text
# ------------------------------------------------------------------------------
[colors.text]
default = "<color>"          # primary text color
muted = "<color>"            # less important text
danger = "<color>"           # destructive/warning text
success = "<color>"          # confirmation text

# ------------------------------------------------------------------------------
# Surfaces & Backgrounds
# ------------------------------------------------------------------------------
[colors.backgrounds]
main = "<color>"              # main window background
secondary = "<color>"         # surfaces on top of main background
secondary_border = "<color>"  # border around secondary surfaces

# ------------------------------------------------------------------------------
# Borders
# ------------------------------------------------------------------------------
[colors.border]
default = "<color>"           # default border
main_window = "<color>"       # outer main window border
settings_window = "<color>"   # outer settings window border
input = "<color>"             # generic input border
input_focus = "<color>"       # input border when focused
input_error = "<color>"       # input border in error state

# ------------------------------------------------------------------------------
# Interactive States
# ------------------------------------------------------------------------------
[colors.interactive]
selection_background = "<color>"          # selected item background
selection_foreground = "<color>"          # text/icon on selected background
hover_background = "<color>"              # background on hover
secondary_selection_background = "<color>" # selection background on secondary surfaces
secondary_selection_foreground = "<color>" # text/icon on secondary selection

# ------------------------------------------------------------------------------
# Scrollbars
# ------------------------------------------------------------------------------
[colors.scrollbars]
default = "<color>"
secondary = "<color>"

# ------------------------------------------------------------------------------
# Links
# ------------------------------------------------------------------------------
[colors.links]
default = "<color>"
visited = "<color>"

# ------------------------------------------------------------------------------
# Text Selection (input fields)
# ------------------------------------------------------------------------------
[colors.text_selection]
background = "<color>"
foreground = "<color>"

# ------------------------------------------------------------------------------
# Tooltips
# ------------------------------------------------------------------------------
[colors.tooltip]
background = "<color>"
foreground = "<color>"

# ------------------------------------------------------------------------------
# Loading / Activity
# ------------------------------------------------------------------------------
[colors.activity]
loading_bar = "<color>"
spinner = "<color>"
