# This file demonstrates all available theme configuration options for Vicinae.
# You don't need to define all of these: only override what you want to customize.
# Undefined colors will be automatically derived from core colors or inherited from base themes.
#
# Check out the full documentation at https://docs.vicinae.com/theming/getting-started

[meta]
name = "Vicinae Dark"
description = "Default Vicinae dark palette"
variant = "dark"                              # "dark" | "light": impacts what icon to show in some circumstances
inherits = "vicinae-dark"
icon = "icons/theme-name.png"                 # Optional: path to theme icon (relative to the theme directory it is placed in if not an absolute path)

[colors.core]
accent = "#b8944e"
accent_foreground = "#0f1014"
background = "#0f1014"
foreground = "#e7e5e4"
secondary_background = "#15161b"
border = "#2a241c"

[colors.main_window]
border = "#2a241c"
footer = { background = "colors.core.secondary_background" }

[colors.settings_window]
border = "#2a241c"

[colors.accents]
blue = "#2f6fed"
green = "#3a9c61"
magenta = "#bc8cff"
orange = "#f0883e"
red = "#b9543b"
yellow = "#c9a76e"
cyan = "#18a5b3"
purple = "#bc8cff"

# For now, shortcuts cannot have their own dedicated background
[colors.shortcut]
border = "colors.core.border"

[colors.text]
default = "colors.core.foreground"
muted = "#a8a29e"
danger = "#b9543b"
success = "#3a9c61"
placeholder = "#78716c"
selection = { background = "#b8944e", foreground = "#0f1014" }

[colors.text.links]
default = "#c9a76e"
visited = "#bc8cff"

[colors.input]
border = "#2a241c"
border_focus = "#b8944e"
border_error = "#b9543b"

[colors.button.primary]
background = "#1c1d23"
foreground = "#e7e5e4"
hover = { background = "#bb1c1d23" }
focus = { outline = "colors.core.accent" }

[colors.list.item.hover]
foreground = "#e7e5e4"
secondary_foreground = "#e7e5e4"

[colors.list.item.selection]
background = "#1c1d23"
foreground = "#e7e5e4"
secondary_background = "#1c1d23"
secondary_foreground = "#e7e5e4"

[colors.grid.item]
background = "#15161b"
hover = { outline = "#e7e5e4" }
selection = { outline = "#e7e5e4" }

[colors.scrollbars]
background = "#2a241c"

[colors.loading]
bar = "#b8944e"
spinner = "#e7e5e4"
