// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.1
// source: command.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { AckResponse } from "./common";

export const protobufPackage = "proto.ext.command";

export interface UpdateCommandMetadataRequest {
  /** Null/empty clears the override. */
  subtitle?: string | undefined;
}

export interface Request {
  updateCommandMetadata?: UpdateCommandMetadataRequest | undefined;
}

export interface Response {
  updateCommandMetadata?: AckResponse | undefined;
}

function createBaseUpdateCommandMetadataRequest(): UpdateCommandMetadataRequest {
  return { subtitle: undefined };
}

export const UpdateCommandMetadataRequest: MessageFns<UpdateCommandMetadataRequest> = {
  encode(message: UpdateCommandMetadataRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.subtitle !== undefined) {
      writer.uint32(10).string(message.subtitle);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateCommandMetadataRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateCommandMetadataRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.subtitle = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateCommandMetadataRequest {
    return { subtitle: isSet(object.subtitle) ? globalThis.String(object.subtitle) : undefined };
  },

  toJSON(message: UpdateCommandMetadataRequest): unknown {
    const obj: any = {};
    if (message.subtitle !== undefined) {
      obj.subtitle = message.subtitle;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateCommandMetadataRequest>, I>>(base?: I): UpdateCommandMetadataRequest {
    return UpdateCommandMetadataRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateCommandMetadataRequest>, I>>(object: I): UpdateCommandMetadataRequest {
    const message = createBaseUpdateCommandMetadataRequest();
    message.subtitle = object.subtitle ?? undefined;
    return message;
  },
};

function createBaseRequest(): Request {
  return { updateCommandMetadata: undefined };
}

export const Request: MessageFns<Request> = {
  encode(message: Request, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.updateCommandMetadata !== undefined) {
      UpdateCommandMetadataRequest.encode(message.updateCommandMetadata, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Request {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.updateCommandMetadata = UpdateCommandMetadataRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Request {
    return {
      updateCommandMetadata: isSet(object.updateCommandMetadata)
        ? UpdateCommandMetadataRequest.fromJSON(object.updateCommandMetadata)
        : undefined,
    };
  },

  toJSON(message: Request): unknown {
    const obj: any = {};
    if (message.updateCommandMetadata !== undefined) {
      obj.updateCommandMetadata = UpdateCommandMetadataRequest.toJSON(message.updateCommandMetadata);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Request>, I>>(base?: I): Request {
    return Request.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Request>, I>>(object: I): Request {
    const message = createBaseRequest();
    message.updateCommandMetadata =
      (object.updateCommandMetadata !== undefined && object.updateCommandMetadata !== null)
        ? UpdateCommandMetadataRequest.fromPartial(object.updateCommandMetadata)
        : undefined;
    return message;
  },
};

function createBaseResponse(): Response {
  return { updateCommandMetadata: undefined };
}

export const Response: MessageFns<Response> = {
  encode(message: Response, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.updateCommandMetadata !== undefined) {
      AckResponse.encode(message.updateCommandMetadata, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Response {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.updateCommandMetadata = AckResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Response {
    return {
      updateCommandMetadata: isSet(object.updateCommandMetadata)
        ? AckResponse.fromJSON(object.updateCommandMetadata)
        : undefined,
    };
  },

  toJSON(message: Response): unknown {
    const obj: any = {};
    if (message.updateCommandMetadata !== undefined) {
      obj.updateCommandMetadata = AckResponse.toJSON(message.updateCommandMetadata);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Response>, I>>(base?: I): Response {
    return Response.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Response>, I>>(object: I): Response {
    const message = createBaseResponse();
    message.updateCommandMetadata =
      (object.updateCommandMetadata !== undefined && object.updateCommandMetadata !== null)
        ? AckResponse.fromPartial(object.updateCommandMetadata)
        : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
