// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.1
// source: extension.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Request as Request2, Response as Response10 } from "./application";
import { Request as Request3, Response as Response11 } from "./clipboard";
import { Request as Request8, Response as Response16 } from "./command";
import { ErrorResponse } from "./common";
import { Request as Request6, Response as Response14 } from "./file-search";
import { Value } from "./google/protobuf/struct";
import { CommandMode, commandModeFromJSON, commandModeToJSON } from "./manager";
import { Request as Request5, Response as Response13 } from "./oauth";
import { Request as Request4, Response as Response12 } from "./storage";
import { Request as Request1, Response as Response9 } from "./ui";
import { Request as Request7, Response as Response15 } from "./wm";

export const protobufPackage = "proto.ext.extension";

export interface Request {
  requestId: string;
  data: RequestData | undefined;
}

export interface RequestData {
  ui?: Request1 | undefined;
  app?: Request2 | undefined;
  clipboard?: Request3 | undefined;
  storage?: Request4 | undefined;
  oauth?: Request5 | undefined;
  fileSearch?: Request6 | undefined;
  wm?: Request7 | undefined;
  command?: Request8 | undefined;
}

export interface Response {
  requestId: string;
  data?: ResponseData | undefined;
  error?: ErrorResponse | undefined;
}

export interface ResponseData {
  ui?: Response9 | undefined;
  app?: Response10 | undefined;
  clipboard?: Response11 | undefined;
  storage?: Response12 | undefined;
  oauth?: Response13 | undefined;
  fileSearch?: Response14 | undefined;
  wm?: Response15 | undefined;
  command?: Response16 | undefined;
}

export interface Event {
  id: string;
  generic?: GenericEventData | undefined;
  crash?: CrashEventData | undefined;
  launch?: LaunchEventData | undefined;
}

export interface CrashEventData {
  text: string;
}

export interface GenericEventData {
  json: string;
}

export interface LaunchEventData {
  extensionName: string;
  commandName: string;
  mode: CommandMode;
  entrypoint: string;
  assetPath: string;
  supportPath: string;
  preferenceValues: { [key: string]: any | undefined };
  argumentValues: { [key: string]: any | undefined };
  isRaycast: boolean;
  ownerOrAuthorName: string;
}

export interface LaunchEventData_PreferenceValuesEntry {
  key: string;
  value: any | undefined;
}

export interface LaunchEventData_ArgumentValuesEntry {
  key: string;
  value: any | undefined;
}

function createBaseRequest(): Request {
  return { requestId: "", data: undefined };
}

export const Request: MessageFns<Request> = {
  encode(message: Request, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.requestId !== "") {
      writer.uint32(10).string(message.requestId);
    }
    if (message.data !== undefined) {
      RequestData.encode(message.data, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Request {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.data = RequestData.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Request {
    return {
      requestId: isSet(object.requestId) ? globalThis.String(object.requestId) : "",
      data: isSet(object.data) ? RequestData.fromJSON(object.data) : undefined,
    };
  },

  toJSON(message: Request): unknown {
    const obj: any = {};
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.data !== undefined) {
      obj.data = RequestData.toJSON(message.data);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Request>, I>>(base?: I): Request {
    return Request.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Request>, I>>(object: I): Request {
    const message = createBaseRequest();
    message.requestId = object.requestId ?? "";
    message.data = (object.data !== undefined && object.data !== null)
      ? RequestData.fromPartial(object.data)
      : undefined;
    return message;
  },
};

function createBaseRequestData(): RequestData {
  return {
    ui: undefined,
    app: undefined,
    clipboard: undefined,
    storage: undefined,
    oauth: undefined,
    fileSearch: undefined,
    wm: undefined,
    command: undefined,
  };
}

export const RequestData: MessageFns<RequestData> = {
  encode(message: RequestData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ui !== undefined) {
      Request1.encode(message.ui, writer.uint32(10).fork()).join();
    }
    if (message.app !== undefined) {
      Request2.encode(message.app, writer.uint32(18).fork()).join();
    }
    if (message.clipboard !== undefined) {
      Request3.encode(message.clipboard, writer.uint32(26).fork()).join();
    }
    if (message.storage !== undefined) {
      Request4.encode(message.storage, writer.uint32(34).fork()).join();
    }
    if (message.oauth !== undefined) {
      Request5.encode(message.oauth, writer.uint32(42).fork()).join();
    }
    if (message.fileSearch !== undefined) {
      Request6.encode(message.fileSearch, writer.uint32(50).fork()).join();
    }
    if (message.wm !== undefined) {
      Request7.encode(message.wm, writer.uint32(58).fork()).join();
    }
    if (message.command !== undefined) {
      Request8.encode(message.command, writer.uint32(66).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RequestData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequestData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.ui = Request1.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.app = Request2.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.clipboard = Request3.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.storage = Request4.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.oauth = Request5.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.fileSearch = Request6.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.wm = Request7.decode(reader, reader.uint32());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.command = Request8.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RequestData {
    return {
      ui: isSet(object.ui) ? Request1.fromJSON(object.ui) : undefined,
      app: isSet(object.app) ? Request2.fromJSON(object.app) : undefined,
      clipboard: isSet(object.clipboard) ? Request3.fromJSON(object.clipboard) : undefined,
      storage: isSet(object.storage) ? Request4.fromJSON(object.storage) : undefined,
      oauth: isSet(object.oauth) ? Request5.fromJSON(object.oauth) : undefined,
      fileSearch: isSet(object.fileSearch) ? Request6.fromJSON(object.fileSearch) : undefined,
      wm: isSet(object.wm) ? Request7.fromJSON(object.wm) : undefined,
      command: isSet(object.command) ? Request8.fromJSON(object.command) : undefined,
    };
  },

  toJSON(message: RequestData): unknown {
    const obj: any = {};
    if (message.ui !== undefined) {
      obj.ui = Request1.toJSON(message.ui);
    }
    if (message.app !== undefined) {
      obj.app = Request2.toJSON(message.app);
    }
    if (message.clipboard !== undefined) {
      obj.clipboard = Request3.toJSON(message.clipboard);
    }
    if (message.storage !== undefined) {
      obj.storage = Request4.toJSON(message.storage);
    }
    if (message.oauth !== undefined) {
      obj.oauth = Request5.toJSON(message.oauth);
    }
    if (message.fileSearch !== undefined) {
      obj.fileSearch = Request6.toJSON(message.fileSearch);
    }
    if (message.wm !== undefined) {
      obj.wm = Request7.toJSON(message.wm);
    }
    if (message.command !== undefined) {
      obj.command = Request8.toJSON(message.command);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RequestData>, I>>(base?: I): RequestData {
    return RequestData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RequestData>, I>>(object: I): RequestData {
    const message = createBaseRequestData();
    message.ui = (object.ui !== undefined && object.ui !== null) ? Request1.fromPartial(object.ui) : undefined;
    message.app = (object.app !== undefined && object.app !== null) ? Request2.fromPartial(object.app) : undefined;
    message.clipboard = (object.clipboard !== undefined && object.clipboard !== null)
      ? Request3.fromPartial(object.clipboard)
      : undefined;
    message.storage = (object.storage !== undefined && object.storage !== null)
      ? Request4.fromPartial(object.storage)
      : undefined;
    message.oauth = (object.oauth !== undefined && object.oauth !== null)
      ? Request5.fromPartial(object.oauth)
      : undefined;
    message.fileSearch = (object.fileSearch !== undefined && object.fileSearch !== null)
      ? Request6.fromPartial(object.fileSearch)
      : undefined;
    message.wm = (object.wm !== undefined && object.wm !== null) ? Request7.fromPartial(object.wm) : undefined;
    message.command = (object.command !== undefined && object.command !== null)
      ? Request8.fromPartial(object.command)
      : undefined;
    return message;
  },
};

function createBaseResponse(): Response {
  return { requestId: "", data: undefined, error: undefined };
}

export const Response: MessageFns<Response> = {
  encode(message: Response, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.requestId !== "") {
      writer.uint32(10).string(message.requestId);
    }
    if (message.data !== undefined) {
      ResponseData.encode(message.data, writer.uint32(18).fork()).join();
    }
    if (message.error !== undefined) {
      ErrorResponse.encode(message.error, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Response {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.data = ResponseData.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.error = ErrorResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Response {
    return {
      requestId: isSet(object.requestId) ? globalThis.String(object.requestId) : "",
      data: isSet(object.data) ? ResponseData.fromJSON(object.data) : undefined,
      error: isSet(object.error) ? ErrorResponse.fromJSON(object.error) : undefined,
    };
  },

  toJSON(message: Response): unknown {
    const obj: any = {};
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.data !== undefined) {
      obj.data = ResponseData.toJSON(message.data);
    }
    if (message.error !== undefined) {
      obj.error = ErrorResponse.toJSON(message.error);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Response>, I>>(base?: I): Response {
    return Response.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Response>, I>>(object: I): Response {
    const message = createBaseResponse();
    message.requestId = object.requestId ?? "";
    message.data = (object.data !== undefined && object.data !== null)
      ? ResponseData.fromPartial(object.data)
      : undefined;
    message.error = (object.error !== undefined && object.error !== null)
      ? ErrorResponse.fromPartial(object.error)
      : undefined;
    return message;
  },
};

function createBaseResponseData(): ResponseData {
  return {
    ui: undefined,
    app: undefined,
    clipboard: undefined,
    storage: undefined,
    oauth: undefined,
    fileSearch: undefined,
    wm: undefined,
    command: undefined,
  };
}

export const ResponseData: MessageFns<ResponseData> = {
  encode(message: ResponseData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ui !== undefined) {
      Response9.encode(message.ui, writer.uint32(10).fork()).join();
    }
    if (message.app !== undefined) {
      Response10.encode(message.app, writer.uint32(18).fork()).join();
    }
    if (message.clipboard !== undefined) {
      Response11.encode(message.clipboard, writer.uint32(26).fork()).join();
    }
    if (message.storage !== undefined) {
      Response12.encode(message.storage, writer.uint32(34).fork()).join();
    }
    if (message.oauth !== undefined) {
      Response13.encode(message.oauth, writer.uint32(42).fork()).join();
    }
    if (message.fileSearch !== undefined) {
      Response14.encode(message.fileSearch, writer.uint32(50).fork()).join();
    }
    if (message.wm !== undefined) {
      Response15.encode(message.wm, writer.uint32(58).fork()).join();
    }
    if (message.command !== undefined) {
      Response16.encode(message.command, writer.uint32(66).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ResponseData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResponseData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.ui = Response9.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.app = Response10.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.clipboard = Response11.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.storage = Response12.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.oauth = Response13.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.fileSearch = Response14.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.wm = Response15.decode(reader, reader.uint32());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.command = Response16.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ResponseData {
    return {
      ui: isSet(object.ui) ? Response9.fromJSON(object.ui) : undefined,
      app: isSet(object.app) ? Response10.fromJSON(object.app) : undefined,
      clipboard: isSet(object.clipboard) ? Response11.fromJSON(object.clipboard) : undefined,
      storage: isSet(object.storage) ? Response12.fromJSON(object.storage) : undefined,
      oauth: isSet(object.oauth) ? Response13.fromJSON(object.oauth) : undefined,
      fileSearch: isSet(object.fileSearch) ? Response14.fromJSON(object.fileSearch) : undefined,
      wm: isSet(object.wm) ? Response15.fromJSON(object.wm) : undefined,
      command: isSet(object.command) ? Response16.fromJSON(object.command) : undefined,
    };
  },

  toJSON(message: ResponseData): unknown {
    const obj: any = {};
    if (message.ui !== undefined) {
      obj.ui = Response9.toJSON(message.ui);
    }
    if (message.app !== undefined) {
      obj.app = Response10.toJSON(message.app);
    }
    if (message.clipboard !== undefined) {
      obj.clipboard = Response11.toJSON(message.clipboard);
    }
    if (message.storage !== undefined) {
      obj.storage = Response12.toJSON(message.storage);
    }
    if (message.oauth !== undefined) {
      obj.oauth = Response13.toJSON(message.oauth);
    }
    if (message.fileSearch !== undefined) {
      obj.fileSearch = Response14.toJSON(message.fileSearch);
    }
    if (message.wm !== undefined) {
      obj.wm = Response15.toJSON(message.wm);
    }
    if (message.command !== undefined) {
      obj.command = Response16.toJSON(message.command);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ResponseData>, I>>(base?: I): ResponseData {
    return ResponseData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ResponseData>, I>>(object: I): ResponseData {
    const message = createBaseResponseData();
    message.ui = (object.ui !== undefined && object.ui !== null) ? Response9.fromPartial(object.ui) : undefined;
    message.app = (object.app !== undefined && object.app !== null) ? Response10.fromPartial(object.app) : undefined;
    message.clipboard = (object.clipboard !== undefined && object.clipboard !== null)
      ? Response11.fromPartial(object.clipboard)
      : undefined;
    message.storage = (object.storage !== undefined && object.storage !== null)
      ? Response12.fromPartial(object.storage)
      : undefined;
    message.oauth = (object.oauth !== undefined && object.oauth !== null)
      ? Response13.fromPartial(object.oauth)
      : undefined;
    message.fileSearch = (object.fileSearch !== undefined && object.fileSearch !== null)
      ? Response14.fromPartial(object.fileSearch)
      : undefined;
    message.wm = (object.wm !== undefined && object.wm !== null) ? Response15.fromPartial(object.wm) : undefined;
    message.command = (object.command !== undefined && object.command !== null)
      ? Response16.fromPartial(object.command)
      : undefined;
    return message;
  },
};

function createBaseEvent(): Event {
  return { id: "", generic: undefined, crash: undefined, launch: undefined };
}

export const Event: MessageFns<Event> = {
  encode(message: Event, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.generic !== undefined) {
      GenericEventData.encode(message.generic, writer.uint32(18).fork()).join();
    }
    if (message.crash !== undefined) {
      CrashEventData.encode(message.crash, writer.uint32(26).fork()).join();
    }
    if (message.launch !== undefined) {
      LaunchEventData.encode(message.launch, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Event {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.generic = GenericEventData.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.crash = CrashEventData.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.launch = LaunchEventData.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Event {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      generic: isSet(object.generic) ? GenericEventData.fromJSON(object.generic) : undefined,
      crash: isSet(object.crash) ? CrashEventData.fromJSON(object.crash) : undefined,
      launch: isSet(object.launch) ? LaunchEventData.fromJSON(object.launch) : undefined,
    };
  },

  toJSON(message: Event): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.generic !== undefined) {
      obj.generic = GenericEventData.toJSON(message.generic);
    }
    if (message.crash !== undefined) {
      obj.crash = CrashEventData.toJSON(message.crash);
    }
    if (message.launch !== undefined) {
      obj.launch = LaunchEventData.toJSON(message.launch);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Event>, I>>(base?: I): Event {
    return Event.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Event>, I>>(object: I): Event {
    const message = createBaseEvent();
    message.id = object.id ?? "";
    message.generic = (object.generic !== undefined && object.generic !== null)
      ? GenericEventData.fromPartial(object.generic)
      : undefined;
    message.crash = (object.crash !== undefined && object.crash !== null)
      ? CrashEventData.fromPartial(object.crash)
      : undefined;
    message.launch = (object.launch !== undefined && object.launch !== null)
      ? LaunchEventData.fromPartial(object.launch)
      : undefined;
    return message;
  },
};

function createBaseCrashEventData(): CrashEventData {
  return { text: "" };
}

export const CrashEventData: MessageFns<CrashEventData> = {
  encode(message: CrashEventData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.text !== "") {
      writer.uint32(10).string(message.text);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CrashEventData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCrashEventData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.text = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CrashEventData {
    return { text: isSet(object.text) ? globalThis.String(object.text) : "" };
  },

  toJSON(message: CrashEventData): unknown {
    const obj: any = {};
    if (message.text !== "") {
      obj.text = message.text;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CrashEventData>, I>>(base?: I): CrashEventData {
    return CrashEventData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CrashEventData>, I>>(object: I): CrashEventData {
    const message = createBaseCrashEventData();
    message.text = object.text ?? "";
    return message;
  },
};

function createBaseGenericEventData(): GenericEventData {
  return { json: "" };
}

export const GenericEventData: MessageFns<GenericEventData> = {
  encode(message: GenericEventData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.json !== "") {
      writer.uint32(10).string(message.json);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GenericEventData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGenericEventData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.json = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GenericEventData {
    return { json: isSet(object.json) ? globalThis.String(object.json) : "" };
  },

  toJSON(message: GenericEventData): unknown {
    const obj: any = {};
    if (message.json !== "") {
      obj.json = message.json;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GenericEventData>, I>>(base?: I): GenericEventData {
    return GenericEventData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GenericEventData>, I>>(object: I): GenericEventData {
    const message = createBaseGenericEventData();
    message.json = object.json ?? "";
    return message;
  },
};

function createBaseLaunchEventData(): LaunchEventData {
  return {
    extensionName: "",
    commandName: "",
    mode: 0,
    entrypoint: "",
    assetPath: "",
    supportPath: "",
    preferenceValues: {},
    argumentValues: {},
    isRaycast: false,
    ownerOrAuthorName: "",
  };
}

export const LaunchEventData: MessageFns<LaunchEventData> = {
  encode(message: LaunchEventData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.extensionName !== "") {
      writer.uint32(10).string(message.extensionName);
    }
    if (message.commandName !== "") {
      writer.uint32(18).string(message.commandName);
    }
    if (message.mode !== 0) {
      writer.uint32(24).int32(message.mode);
    }
    if (message.entrypoint !== "") {
      writer.uint32(34).string(message.entrypoint);
    }
    if (message.assetPath !== "") {
      writer.uint32(42).string(message.assetPath);
    }
    if (message.supportPath !== "") {
      writer.uint32(50).string(message.supportPath);
    }
    Object.entries(message.preferenceValues).forEach(([key, value]) => {
      if (value !== undefined) {
        LaunchEventData_PreferenceValuesEntry.encode({ key: key as any, value }, writer.uint32(58).fork()).join();
      }
    });
    Object.entries(message.argumentValues).forEach(([key, value]) => {
      if (value !== undefined) {
        LaunchEventData_ArgumentValuesEntry.encode({ key: key as any, value }, writer.uint32(66).fork()).join();
      }
    });
    if (message.isRaycast !== false) {
      writer.uint32(72).bool(message.isRaycast);
    }
    if (message.ownerOrAuthorName !== "") {
      writer.uint32(82).string(message.ownerOrAuthorName);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LaunchEventData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLaunchEventData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.extensionName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.commandName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.mode = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.entrypoint = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.assetPath = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.supportPath = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          const entry7 = LaunchEventData_PreferenceValuesEntry.decode(reader, reader.uint32());
          if (entry7.value !== undefined) {
            message.preferenceValues[entry7.key] = entry7.value;
          }
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          const entry8 = LaunchEventData_ArgumentValuesEntry.decode(reader, reader.uint32());
          if (entry8.value !== undefined) {
            message.argumentValues[entry8.key] = entry8.value;
          }
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.isRaycast = reader.bool();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.ownerOrAuthorName = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LaunchEventData {
    return {
      extensionName: isSet(object.extensionName) ? globalThis.String(object.extensionName) : "",
      commandName: isSet(object.commandName) ? globalThis.String(object.commandName) : "",
      mode: isSet(object.mode) ? commandModeFromJSON(object.mode) : 0,
      entrypoint: isSet(object.entrypoint) ? globalThis.String(object.entrypoint) : "",
      assetPath: isSet(object.assetPath) ? globalThis.String(object.assetPath) : "",
      supportPath: isSet(object.supportPath) ? globalThis.String(object.supportPath) : "",
      preferenceValues: isObject(object.preferenceValues)
        ? Object.entries(object.preferenceValues).reduce<{ [key: string]: any | undefined }>((acc, [key, value]) => {
          acc[key] = value as any | undefined;
          return acc;
        }, {})
        : {},
      argumentValues: isObject(object.argumentValues)
        ? Object.entries(object.argumentValues).reduce<{ [key: string]: any | undefined }>((acc, [key, value]) => {
          acc[key] = value as any | undefined;
          return acc;
        }, {})
        : {},
      isRaycast: isSet(object.isRaycast) ? globalThis.Boolean(object.isRaycast) : false,
      ownerOrAuthorName: isSet(object.ownerOrAuthorName) ? globalThis.String(object.ownerOrAuthorName) : "",
    };
  },

  toJSON(message: LaunchEventData): unknown {
    const obj: any = {};
    if (message.extensionName !== "") {
      obj.extensionName = message.extensionName;
    }
    if (message.commandName !== "") {
      obj.commandName = message.commandName;
    }
    if (message.mode !== 0) {
      obj.mode = commandModeToJSON(message.mode);
    }
    if (message.entrypoint !== "") {
      obj.entrypoint = message.entrypoint;
    }
    if (message.assetPath !== "") {
      obj.assetPath = message.assetPath;
    }
    if (message.supportPath !== "") {
      obj.supportPath = message.supportPath;
    }
    if (message.preferenceValues) {
      const entries = Object.entries(message.preferenceValues);
      if (entries.length > 0) {
        obj.preferenceValues = {};
        entries.forEach(([k, v]) => {
          obj.preferenceValues[k] = v;
        });
      }
    }
    if (message.argumentValues) {
      const entries = Object.entries(message.argumentValues);
      if (entries.length > 0) {
        obj.argumentValues = {};
        entries.forEach(([k, v]) => {
          obj.argumentValues[k] = v;
        });
      }
    }
    if (message.isRaycast !== false) {
      obj.isRaycast = message.isRaycast;
    }
    if (message.ownerOrAuthorName !== "") {
      obj.ownerOrAuthorName = message.ownerOrAuthorName;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LaunchEventData>, I>>(base?: I): LaunchEventData {
    return LaunchEventData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LaunchEventData>, I>>(object: I): LaunchEventData {
    const message = createBaseLaunchEventData();
    message.extensionName = object.extensionName ?? "";
    message.commandName = object.commandName ?? "";
    message.mode = object.mode ?? 0;
    message.entrypoint = object.entrypoint ?? "";
    message.assetPath = object.assetPath ?? "";
    message.supportPath = object.supportPath ?? "";
    message.preferenceValues = Object.entries(object.preferenceValues ?? {}).reduce<{ [key: string]: any | undefined }>(
      (acc, [key, value]) => {
        if (value !== undefined) {
          acc[key] = value;
        }
        return acc;
      },
      {},
    );
    message.argumentValues = Object.entries(object.argumentValues ?? {}).reduce<{ [key: string]: any | undefined }>(
      (acc, [key, value]) => {
        if (value !== undefined) {
          acc[key] = value;
        }
        return acc;
      },
      {},
    );
    message.isRaycast = object.isRaycast ?? false;
    message.ownerOrAuthorName = object.ownerOrAuthorName ?? "";
    return message;
  },
};

function createBaseLaunchEventData_PreferenceValuesEntry(): LaunchEventData_PreferenceValuesEntry {
  return { key: "", value: undefined };
}

export const LaunchEventData_PreferenceValuesEntry: MessageFns<LaunchEventData_PreferenceValuesEntry> = {
  encode(message: LaunchEventData_PreferenceValuesEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== undefined) {
      Value.encode(Value.wrap(message.value), writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LaunchEventData_PreferenceValuesEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLaunchEventData_PreferenceValuesEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = Value.unwrap(Value.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LaunchEventData_PreferenceValuesEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object?.value) ? object.value : undefined,
    };
  },

  toJSON(message: LaunchEventData_PreferenceValuesEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== undefined) {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LaunchEventData_PreferenceValuesEntry>, I>>(
    base?: I,
  ): LaunchEventData_PreferenceValuesEntry {
    return LaunchEventData_PreferenceValuesEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LaunchEventData_PreferenceValuesEntry>, I>>(
    object: I,
  ): LaunchEventData_PreferenceValuesEntry {
    const message = createBaseLaunchEventData_PreferenceValuesEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? undefined;
    return message;
  },
};

function createBaseLaunchEventData_ArgumentValuesEntry(): LaunchEventData_ArgumentValuesEntry {
  return { key: "", value: undefined };
}

export const LaunchEventData_ArgumentValuesEntry: MessageFns<LaunchEventData_ArgumentValuesEntry> = {
  encode(message: LaunchEventData_ArgumentValuesEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== undefined) {
      Value.encode(Value.wrap(message.value), writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LaunchEventData_ArgumentValuesEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLaunchEventData_ArgumentValuesEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = Value.unwrap(Value.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LaunchEventData_ArgumentValuesEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object?.value) ? object.value : undefined,
    };
  },

  toJSON(message: LaunchEventData_ArgumentValuesEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== undefined) {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LaunchEventData_ArgumentValuesEntry>, I>>(
    base?: I,
  ): LaunchEventData_ArgumentValuesEntry {
    return LaunchEventData_ArgumentValuesEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LaunchEventData_ArgumentValuesEntry>, I>>(
    object: I,
  ): LaunchEventData_ArgumentValuesEntry {
    const message = createBaseLaunchEventData_ArgumentValuesEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
