// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.1
// source: oauth.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Image } from "./ui";

export const protobufPackage = "proto.ext.oauth";

export enum RedirectMethod {
  Web = 0,
  App = 1,
  AppURI = 2,
  UNRECOGNIZED = -1,
}

export function redirectMethodFromJSON(object: any): RedirectMethod {
  switch (object) {
    case 0:
    case "Web":
      return RedirectMethod.Web;
    case 1:
    case "App":
      return RedirectMethod.App;
    case 2:
    case "AppURI":
      return RedirectMethod.AppURI;
    case -1:
    case "UNRECOGNIZED":
    default:
      return RedirectMethod.UNRECOGNIZED;
  }
}

export function redirectMethodToJSON(object: RedirectMethod): string {
  switch (object) {
    case RedirectMethod.Web:
      return "Web";
    case RedirectMethod.App:
      return "App";
    case RedirectMethod.AppURI:
      return "AppURI";
    case RedirectMethod.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface PKCEClientOptions {
  id?: string | undefined;
  name: string;
  /** we need to implement image like schema */
  description: string;
  icon?: Image | undefined;
}

export interface AuthorizeRequest {
  client: PKCEClientOptions | undefined;
  url: string;
}

export interface TokenSet {
  accessToken: string;
  refreshToken?: string | undefined;
  idToken?: string | undefined;
  expiresIn?: number | undefined;
  scope?: string | undefined;
  updatedAt: number;
}

export interface GetTokensRequest {
  providerId?: string | undefined;
}

export interface GetTokensResponse {
  tokenSet: TokenSet | undefined;
}

export interface SetTokensRequest {
  providerId?: string | undefined;
  accessToken: string;
  refreshToken?: string | undefined;
  idToken?: string | undefined;
  expiresIn?: number | undefined;
  scope?: string | undefined;
}

export interface SetTokensResponse {
}

export interface RemoveTokensRequest {
  providerId?: string | undefined;
}

export interface RemoveTokensResponse {
}

export interface AuthorizeResponse {
  code: string;
}

export interface Request {
  authorize?: AuthorizeRequest | undefined;
  getTokens?: GetTokensRequest | undefined;
  setTokens?: SetTokensRequest | undefined;
  removeTokens?: RemoveTokensRequest | undefined;
}

export interface Response {
  authorize?: AuthorizeResponse | undefined;
  getTokens?: GetTokensResponse | undefined;
  setTokens?: SetTokensResponse | undefined;
  removeTokens?: RemoveTokensResponse | undefined;
}

function createBasePKCEClientOptions(): PKCEClientOptions {
  return { id: undefined, name: "", description: "", icon: undefined };
}

export const PKCEClientOptions: MessageFns<PKCEClientOptions> = {
  encode(message: PKCEClientOptions, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined) {
      writer.uint32(10).string(message.id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.description !== "") {
      writer.uint32(26).string(message.description);
    }
    if (message.icon !== undefined) {
      Image.encode(message.icon, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PKCEClientOptions {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePKCEClientOptions();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.icon = Image.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PKCEClientOptions {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : undefined,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      icon: isSet(object.icon) ? Image.fromJSON(object.icon) : undefined,
    };
  },

  toJSON(message: PKCEClientOptions): unknown {
    const obj: any = {};
    if (message.id !== undefined) {
      obj.id = message.id;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.icon !== undefined) {
      obj.icon = Image.toJSON(message.icon);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PKCEClientOptions>, I>>(base?: I): PKCEClientOptions {
    return PKCEClientOptions.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PKCEClientOptions>, I>>(object: I): PKCEClientOptions {
    const message = createBasePKCEClientOptions();
    message.id = object.id ?? undefined;
    message.name = object.name ?? "";
    message.description = object.description ?? "";
    message.icon = (object.icon !== undefined && object.icon !== null) ? Image.fromPartial(object.icon) : undefined;
    return message;
  },
};

function createBaseAuthorizeRequest(): AuthorizeRequest {
  return { client: undefined, url: "" };
}

export const AuthorizeRequest: MessageFns<AuthorizeRequest> = {
  encode(message: AuthorizeRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.client !== undefined) {
      PKCEClientOptions.encode(message.client, writer.uint32(10).fork()).join();
    }
    if (message.url !== "") {
      writer.uint32(18).string(message.url);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AuthorizeRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAuthorizeRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.client = PKCEClientOptions.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.url = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AuthorizeRequest {
    return {
      client: isSet(object.client) ? PKCEClientOptions.fromJSON(object.client) : undefined,
      url: isSet(object.url) ? globalThis.String(object.url) : "",
    };
  },

  toJSON(message: AuthorizeRequest): unknown {
    const obj: any = {};
    if (message.client !== undefined) {
      obj.client = PKCEClientOptions.toJSON(message.client);
    }
    if (message.url !== "") {
      obj.url = message.url;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AuthorizeRequest>, I>>(base?: I): AuthorizeRequest {
    return AuthorizeRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AuthorizeRequest>, I>>(object: I): AuthorizeRequest {
    const message = createBaseAuthorizeRequest();
    message.client = (object.client !== undefined && object.client !== null)
      ? PKCEClientOptions.fromPartial(object.client)
      : undefined;
    message.url = object.url ?? "";
    return message;
  },
};

function createBaseTokenSet(): TokenSet {
  return {
    accessToken: "",
    refreshToken: undefined,
    idToken: undefined,
    expiresIn: undefined,
    scope: undefined,
    updatedAt: 0,
  };
}

export const TokenSet: MessageFns<TokenSet> = {
  encode(message: TokenSet, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.accessToken !== "") {
      writer.uint32(10).string(message.accessToken);
    }
    if (message.refreshToken !== undefined) {
      writer.uint32(18).string(message.refreshToken);
    }
    if (message.idToken !== undefined) {
      writer.uint32(26).string(message.idToken);
    }
    if (message.expiresIn !== undefined) {
      writer.uint32(32).uint32(message.expiresIn);
    }
    if (message.scope !== undefined) {
      writer.uint32(42).string(message.scope);
    }
    if (message.updatedAt !== 0) {
      writer.uint32(48).uint64(message.updatedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TokenSet {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTokenSet();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.accessToken = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.refreshToken = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.idToken = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.expiresIn = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.scope = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.updatedAt = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TokenSet {
    return {
      accessToken: isSet(object.accessToken) ? globalThis.String(object.accessToken) : "",
      refreshToken: isSet(object.refreshToken) ? globalThis.String(object.refreshToken) : undefined,
      idToken: isSet(object.idToken) ? globalThis.String(object.idToken) : undefined,
      expiresIn: isSet(object.expiresIn) ? globalThis.Number(object.expiresIn) : undefined,
      scope: isSet(object.scope) ? globalThis.String(object.scope) : undefined,
      updatedAt: isSet(object.updatedAt) ? globalThis.Number(object.updatedAt) : 0,
    };
  },

  toJSON(message: TokenSet): unknown {
    const obj: any = {};
    if (message.accessToken !== "") {
      obj.accessToken = message.accessToken;
    }
    if (message.refreshToken !== undefined) {
      obj.refreshToken = message.refreshToken;
    }
    if (message.idToken !== undefined) {
      obj.idToken = message.idToken;
    }
    if (message.expiresIn !== undefined) {
      obj.expiresIn = Math.round(message.expiresIn);
    }
    if (message.scope !== undefined) {
      obj.scope = message.scope;
    }
    if (message.updatedAt !== 0) {
      obj.updatedAt = Math.round(message.updatedAt);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TokenSet>, I>>(base?: I): TokenSet {
    return TokenSet.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TokenSet>, I>>(object: I): TokenSet {
    const message = createBaseTokenSet();
    message.accessToken = object.accessToken ?? "";
    message.refreshToken = object.refreshToken ?? undefined;
    message.idToken = object.idToken ?? undefined;
    message.expiresIn = object.expiresIn ?? undefined;
    message.scope = object.scope ?? undefined;
    message.updatedAt = object.updatedAt ?? 0;
    return message;
  },
};

function createBaseGetTokensRequest(): GetTokensRequest {
  return { providerId: undefined };
}

export const GetTokensRequest: MessageFns<GetTokensRequest> = {
  encode(message: GetTokensRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.providerId !== undefined) {
      writer.uint32(10).string(message.providerId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetTokensRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetTokensRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.providerId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetTokensRequest {
    return { providerId: isSet(object.providerId) ? globalThis.String(object.providerId) : undefined };
  },

  toJSON(message: GetTokensRequest): unknown {
    const obj: any = {};
    if (message.providerId !== undefined) {
      obj.providerId = message.providerId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetTokensRequest>, I>>(base?: I): GetTokensRequest {
    return GetTokensRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetTokensRequest>, I>>(object: I): GetTokensRequest {
    const message = createBaseGetTokensRequest();
    message.providerId = object.providerId ?? undefined;
    return message;
  },
};

function createBaseGetTokensResponse(): GetTokensResponse {
  return { tokenSet: undefined };
}

export const GetTokensResponse: MessageFns<GetTokensResponse> = {
  encode(message: GetTokensResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.tokenSet !== undefined) {
      TokenSet.encode(message.tokenSet, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetTokensResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetTokensResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.tokenSet = TokenSet.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetTokensResponse {
    return { tokenSet: isSet(object.tokenSet) ? TokenSet.fromJSON(object.tokenSet) : undefined };
  },

  toJSON(message: GetTokensResponse): unknown {
    const obj: any = {};
    if (message.tokenSet !== undefined) {
      obj.tokenSet = TokenSet.toJSON(message.tokenSet);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetTokensResponse>, I>>(base?: I): GetTokensResponse {
    return GetTokensResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetTokensResponse>, I>>(object: I): GetTokensResponse {
    const message = createBaseGetTokensResponse();
    message.tokenSet = (object.tokenSet !== undefined && object.tokenSet !== null)
      ? TokenSet.fromPartial(object.tokenSet)
      : undefined;
    return message;
  },
};

function createBaseSetTokensRequest(): SetTokensRequest {
  return {
    providerId: undefined,
    accessToken: "",
    refreshToken: undefined,
    idToken: undefined,
    expiresIn: undefined,
    scope: undefined,
  };
}

export const SetTokensRequest: MessageFns<SetTokensRequest> = {
  encode(message: SetTokensRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.providerId !== undefined) {
      writer.uint32(10).string(message.providerId);
    }
    if (message.accessToken !== "") {
      writer.uint32(18).string(message.accessToken);
    }
    if (message.refreshToken !== undefined) {
      writer.uint32(26).string(message.refreshToken);
    }
    if (message.idToken !== undefined) {
      writer.uint32(34).string(message.idToken);
    }
    if (message.expiresIn !== undefined) {
      writer.uint32(40).uint32(message.expiresIn);
    }
    if (message.scope !== undefined) {
      writer.uint32(50).string(message.scope);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetTokensRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetTokensRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.providerId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.accessToken = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.refreshToken = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.idToken = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.expiresIn = reader.uint32();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.scope = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SetTokensRequest {
    return {
      providerId: isSet(object.providerId) ? globalThis.String(object.providerId) : undefined,
      accessToken: isSet(object.accessToken) ? globalThis.String(object.accessToken) : "",
      refreshToken: isSet(object.refreshToken) ? globalThis.String(object.refreshToken) : undefined,
      idToken: isSet(object.idToken) ? globalThis.String(object.idToken) : undefined,
      expiresIn: isSet(object.expiresIn) ? globalThis.Number(object.expiresIn) : undefined,
      scope: isSet(object.scope) ? globalThis.String(object.scope) : undefined,
    };
  },

  toJSON(message: SetTokensRequest): unknown {
    const obj: any = {};
    if (message.providerId !== undefined) {
      obj.providerId = message.providerId;
    }
    if (message.accessToken !== "") {
      obj.accessToken = message.accessToken;
    }
    if (message.refreshToken !== undefined) {
      obj.refreshToken = message.refreshToken;
    }
    if (message.idToken !== undefined) {
      obj.idToken = message.idToken;
    }
    if (message.expiresIn !== undefined) {
      obj.expiresIn = Math.round(message.expiresIn);
    }
    if (message.scope !== undefined) {
      obj.scope = message.scope;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SetTokensRequest>, I>>(base?: I): SetTokensRequest {
    return SetTokensRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SetTokensRequest>, I>>(object: I): SetTokensRequest {
    const message = createBaseSetTokensRequest();
    message.providerId = object.providerId ?? undefined;
    message.accessToken = object.accessToken ?? "";
    message.refreshToken = object.refreshToken ?? undefined;
    message.idToken = object.idToken ?? undefined;
    message.expiresIn = object.expiresIn ?? undefined;
    message.scope = object.scope ?? undefined;
    return message;
  },
};

function createBaseSetTokensResponse(): SetTokensResponse {
  return {};
}

export const SetTokensResponse: MessageFns<SetTokensResponse> = {
  encode(_: SetTokensResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetTokensResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetTokensResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): SetTokensResponse {
    return {};
  },

  toJSON(_: SetTokensResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<SetTokensResponse>, I>>(base?: I): SetTokensResponse {
    return SetTokensResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SetTokensResponse>, I>>(_: I): SetTokensResponse {
    const message = createBaseSetTokensResponse();
    return message;
  },
};

function createBaseRemoveTokensRequest(): RemoveTokensRequest {
  return { providerId: undefined };
}

export const RemoveTokensRequest: MessageFns<RemoveTokensRequest> = {
  encode(message: RemoveTokensRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.providerId !== undefined) {
      writer.uint32(10).string(message.providerId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RemoveTokensRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRemoveTokensRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.providerId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RemoveTokensRequest {
    return { providerId: isSet(object.providerId) ? globalThis.String(object.providerId) : undefined };
  },

  toJSON(message: RemoveTokensRequest): unknown {
    const obj: any = {};
    if (message.providerId !== undefined) {
      obj.providerId = message.providerId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RemoveTokensRequest>, I>>(base?: I): RemoveTokensRequest {
    return RemoveTokensRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RemoveTokensRequest>, I>>(object: I): RemoveTokensRequest {
    const message = createBaseRemoveTokensRequest();
    message.providerId = object.providerId ?? undefined;
    return message;
  },
};

function createBaseRemoveTokensResponse(): RemoveTokensResponse {
  return {};
}

export const RemoveTokensResponse: MessageFns<RemoveTokensResponse> = {
  encode(_: RemoveTokensResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RemoveTokensResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRemoveTokensResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): RemoveTokensResponse {
    return {};
  },

  toJSON(_: RemoveTokensResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<RemoveTokensResponse>, I>>(base?: I): RemoveTokensResponse {
    return RemoveTokensResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RemoveTokensResponse>, I>>(_: I): RemoveTokensResponse {
    const message = createBaseRemoveTokensResponse();
    return message;
  },
};

function createBaseAuthorizeResponse(): AuthorizeResponse {
  return { code: "" };
}

export const AuthorizeResponse: MessageFns<AuthorizeResponse> = {
  encode(message: AuthorizeResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.code !== "") {
      writer.uint32(10).string(message.code);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AuthorizeResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAuthorizeResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.code = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AuthorizeResponse {
    return { code: isSet(object.code) ? globalThis.String(object.code) : "" };
  },

  toJSON(message: AuthorizeResponse): unknown {
    const obj: any = {};
    if (message.code !== "") {
      obj.code = message.code;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AuthorizeResponse>, I>>(base?: I): AuthorizeResponse {
    return AuthorizeResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AuthorizeResponse>, I>>(object: I): AuthorizeResponse {
    const message = createBaseAuthorizeResponse();
    message.code = object.code ?? "";
    return message;
  },
};

function createBaseRequest(): Request {
  return { authorize: undefined, getTokens: undefined, setTokens: undefined, removeTokens: undefined };
}

export const Request: MessageFns<Request> = {
  encode(message: Request, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.authorize !== undefined) {
      AuthorizeRequest.encode(message.authorize, writer.uint32(10).fork()).join();
    }
    if (message.getTokens !== undefined) {
      GetTokensRequest.encode(message.getTokens, writer.uint32(18).fork()).join();
    }
    if (message.setTokens !== undefined) {
      SetTokensRequest.encode(message.setTokens, writer.uint32(26).fork()).join();
    }
    if (message.removeTokens !== undefined) {
      RemoveTokensRequest.encode(message.removeTokens, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Request {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.authorize = AuthorizeRequest.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.getTokens = GetTokensRequest.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.setTokens = SetTokensRequest.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.removeTokens = RemoveTokensRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Request {
    return {
      authorize: isSet(object.authorize) ? AuthorizeRequest.fromJSON(object.authorize) : undefined,
      getTokens: isSet(object.getTokens) ? GetTokensRequest.fromJSON(object.getTokens) : undefined,
      setTokens: isSet(object.setTokens) ? SetTokensRequest.fromJSON(object.setTokens) : undefined,
      removeTokens: isSet(object.removeTokens) ? RemoveTokensRequest.fromJSON(object.removeTokens) : undefined,
    };
  },

  toJSON(message: Request): unknown {
    const obj: any = {};
    if (message.authorize !== undefined) {
      obj.authorize = AuthorizeRequest.toJSON(message.authorize);
    }
    if (message.getTokens !== undefined) {
      obj.getTokens = GetTokensRequest.toJSON(message.getTokens);
    }
    if (message.setTokens !== undefined) {
      obj.setTokens = SetTokensRequest.toJSON(message.setTokens);
    }
    if (message.removeTokens !== undefined) {
      obj.removeTokens = RemoveTokensRequest.toJSON(message.removeTokens);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Request>, I>>(base?: I): Request {
    return Request.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Request>, I>>(object: I): Request {
    const message = createBaseRequest();
    message.authorize = (object.authorize !== undefined && object.authorize !== null)
      ? AuthorizeRequest.fromPartial(object.authorize)
      : undefined;
    message.getTokens = (object.getTokens !== undefined && object.getTokens !== null)
      ? GetTokensRequest.fromPartial(object.getTokens)
      : undefined;
    message.setTokens = (object.setTokens !== undefined && object.setTokens !== null)
      ? SetTokensRequest.fromPartial(object.setTokens)
      : undefined;
    message.removeTokens = (object.removeTokens !== undefined && object.removeTokens !== null)
      ? RemoveTokensRequest.fromPartial(object.removeTokens)
      : undefined;
    return message;
  },
};

function createBaseResponse(): Response {
  return { authorize: undefined, getTokens: undefined, setTokens: undefined, removeTokens: undefined };
}

export const Response: MessageFns<Response> = {
  encode(message: Response, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.authorize !== undefined) {
      AuthorizeResponse.encode(message.authorize, writer.uint32(10).fork()).join();
    }
    if (message.getTokens !== undefined) {
      GetTokensResponse.encode(message.getTokens, writer.uint32(18).fork()).join();
    }
    if (message.setTokens !== undefined) {
      SetTokensResponse.encode(message.setTokens, writer.uint32(26).fork()).join();
    }
    if (message.removeTokens !== undefined) {
      RemoveTokensResponse.encode(message.removeTokens, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Response {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.authorize = AuthorizeResponse.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.getTokens = GetTokensResponse.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.setTokens = SetTokensResponse.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.removeTokens = RemoveTokensResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Response {
    return {
      authorize: isSet(object.authorize) ? AuthorizeResponse.fromJSON(object.authorize) : undefined,
      getTokens: isSet(object.getTokens) ? GetTokensResponse.fromJSON(object.getTokens) : undefined,
      setTokens: isSet(object.setTokens) ? SetTokensResponse.fromJSON(object.setTokens) : undefined,
      removeTokens: isSet(object.removeTokens) ? RemoveTokensResponse.fromJSON(object.removeTokens) : undefined,
    };
  },

  toJSON(message: Response): unknown {
    const obj: any = {};
    if (message.authorize !== undefined) {
      obj.authorize = AuthorizeResponse.toJSON(message.authorize);
    }
    if (message.getTokens !== undefined) {
      obj.getTokens = GetTokensResponse.toJSON(message.getTokens);
    }
    if (message.setTokens !== undefined) {
      obj.setTokens = SetTokensResponse.toJSON(message.setTokens);
    }
    if (message.removeTokens !== undefined) {
      obj.removeTokens = RemoveTokensResponse.toJSON(message.removeTokens);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Response>, I>>(base?: I): Response {
    return Response.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Response>, I>>(object: I): Response {
    const message = createBaseResponse();
    message.authorize = (object.authorize !== undefined && object.authorize !== null)
      ? AuthorizeResponse.fromPartial(object.authorize)
      : undefined;
    message.getTokens = (object.getTokens !== undefined && object.getTokens !== null)
      ? GetTokensResponse.fromPartial(object.getTokens)
      : undefined;
    message.setTokens = (object.setTokens !== undefined && object.setTokens !== null)
      ? SetTokensResponse.fromPartial(object.setTokens)
      : undefined;
    message.removeTokens = (object.removeTokens !== undefined && object.removeTokens !== null)
      ? RemoveTokensResponse.fromPartial(object.removeTokens)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
