import { CATEGORIES, type Category, type Item } from './categories.ts';

const encoder = new TextEncoder();

export interface Provenance {
	unicode: string;
	emoji: string;
	cldr: string;
}

export function banner(p: Provenance): string {
	return `// Generated by scripts/gen.ts from Unicode ${p.unicode}, Emoji ${p.emoji}, CLDR ${p.cldr} — do not edit by hand.`;
}

// Byte-wise UTF-8 order, matching std::string_view comparison on the C++ side.
function compareUtf8(a: string, b: string): number {
	const ba = encoder.encode(a);
	const bb = encoder.encode(b);
	const n = Math.min(ba.length, bb.length);
	for (let i = 0; i < n; i++) {
		if (ba[i] !== bb[i]) return ba[i] - bb[i];
	}
	return ba.length - bb.length;
}

function cppString(s: string): string {
	let out = '"';
	for (const ch of s) {
		if (ch === '\\') out += '\\\\';
		else if (ch === '"') out += '\\"';
		else if (ch === '\n') out += '\\n';
		else if (ch === '\t') out += '\\t';
		else if (ch === '\r') out += '\\r';
		else out += ch;
	}
	return out + '"';
}

function categoryRuns(items: Item[]): { category: Category; start: number; count: number }[] {
	const runs: { category: Category; start: number; count: number }[] = [];
	items.forEach((item, i) => {
		const last = runs[runs.length - 1];
		if (last && last.category === item.category) last.count++;
		else runs.push({ category: item.category, start: i, count: 1 });
	});
	return runs;
}

export function emitHpp(provenance: Provenance): string {
	const out: string[] = [];
	out.push(banner(provenance));
	out.push('#pragma once');
	out.push('#include <cstdint>');
	out.push('#include <span>');
	out.push('#include <string_view>');
	out.push('');
	out.push('namespace glyph {');
	out.push('');
	out.push('enum class Kind : std::uint8_t {');
	out.push('  Emoji,');
	out.push('  Symbol,');
	out.push('};');
	out.push('');
	out.push('enum class Category : std::uint8_t {');
	for (const c of CATEGORIES) out.push(`  ${c.category},`);
	out.push('};');
	out.push('');
	out.push('struct Item {');
	out.push('  std::string_view character;');
	out.push('  std::string_view name;');
	out.push('  std::span<const std::string_view> keywords;');
	out.push('  Kind kind;');
	out.push('  Category category;');
	out.push('  bool skinnable;');
	out.push('};');
	out.push('');
	out.push('struct Section {');
	out.push('  Category category;');
	out.push('  Kind kind;');
	out.push('  std::string_view label;');
	out.push('  std::span<const Item> members;');
	out.push('};');
	out.push('');
	out.push('std::span<const Item> items();');
	out.push('std::span<const Section> sections();');
	out.push('const Item *lookup(std::string_view character);');
	out.push('std::string_view categoryLabel(Category category);');
	out.push('');
	out.push('}; // namespace glyph');
	out.push('');
	return out.join('\n');
}

// Items are laid out in category order (emoji first, in emoji-test order; symbols by glyph) so every
// category is a contiguous span. A glyph-sorted pointer index backs lookup().
export function emitCpp(symbols: Item[], emojis: Item[], provenance: Provenance): string {
	const rank = new Map<Category, number>(CATEGORIES.map((c, i) => [c.category, i]));
	const info = new Map<Category, (typeof CATEGORIES)[number]>(CATEGORIES.map((c) => [c.category, c]));

	const sortedSymbols = [...symbols].sort(
		(a, b) => (rank.get(a.category)! - rank.get(b.category)!) || compareUtf8(a.character, b.character),
	);
	const g_items = [...emojis, ...sortedSymbols];

	const pool: string[] = [];
	const rowLine = (item: Item): string => {
		let slice = '{}';
		if (item.keywords.length > 0) {
			slice = `{kw_pool.data() + ${pool.length}, ${item.keywords.length}}`;
			pool.push(...item.keywords);
		}
		return (
			`  {${cppString(item.character)}, ${cppString(item.name)}, ${slice}, ` +
			`Kind::${item.kind}, Category::${item.category}, ${item.skinnable}},`
		);
	};
	const itemLines = g_items.map(rowLine);

	const out: string[] = [];
	out.push(banner(provenance));
	out.push('#include "glyph.hpp"');
	out.push('');
	out.push('#include <algorithm>');
	out.push('#include <array>');
	out.push('');
	out.push('using namespace glyph;');
	out.push('');
	out.push('namespace {');
	out.push('');

	if (pool.length > 0) {
		out.push(`constexpr std::array<std::string_view, ${pool.length}> kw_pool = {{`);
		out.push('  ' + pool.map(cppString).join(', '));
		out.push('}};');
		out.push('');
	}

	out.push(`constexpr std::array<Item, ${itemLines.length}> g_items = {{`);
	out.push(...itemLines);
	out.push('}};');
	out.push('');

	const runs = categoryRuns(g_items);
	out.push(`constexpr std::array<Section, ${runs.length}> g_sections = {{`);
	for (const run of runs) {
		const meta = info.get(run.category)!;
		out.push(
			`  {Category::${run.category}, Kind::${meta.kind}, ${cppString(meta.label)}, ` +
				`{g_items.data() + ${run.start}, ${run.count}}},`,
		);
	}
	out.push('}};');
	out.push('');

	const index = g_items
		.map((item, i) => ({ character: item.character, i }))
		.sort((a, b) => compareUtf8(a.character, b.character));
	out.push(`constexpr std::array<const Item *, ${index.length}> g_index = {{`);
	out.push('  ' + index.map((e) => `&g_items[${e.i}]`).join(', '));
	out.push('}};');
	out.push('');
	out.push('} // namespace');
	out.push('');
	out.push('std::span<const Item> glyph::items() { return g_items; }');
	out.push('std::span<const Section> glyph::sections() { return g_sections; }');
	out.push('');
	out.push('const Item *glyph::lookup(std::string_view character) {');
	out.push('  auto it = std::lower_bound(');
	out.push('      g_index.begin(), g_index.end(), character,');
	out.push('      [](const Item *i, std::string_view key) { return i->character < key; });');
	out.push('  if (it != g_index.end() && (*it)->character == character) return *it;');
	out.push('  return nullptr;');
	out.push('}');
	out.push('');

	out.push('std::string_view glyph::categoryLabel(Category category) {');
	out.push('  switch (category) {');
	for (const c of CATEGORIES) {
		out.push(`  case Category::${c.category}: return ${cppString(c.label)};`);
	}
	out.push('  }');
	out.push('  return {};');
	out.push('}');
	out.push('');

	return out.join('\n');
}
