#include "macos-clipboard-server.hpp"

#import <AppKit/AppKit.h>
#import <Foundation/Foundation.h>

#include <QClipboard>
#include <QGuiApplication>
#include <QMimeData>
#include <qlogging.h>

#include "services/clipboard/clipboard-mime.hpp"

namespace {
NSString *const CONCEALED_UTI = @"org.nspasteboard.ConcealedType";
NSString *const TRANSIENT_UTI = @"org.nspasteboard.TransientType";
NSString *const AUTO_GENERATED_UTI = @"org.nspasteboard.AutoGeneratedType";
NSString *const SOURCE_UTI = @"org.nspasteboard.source";
} // namespace

MacosClipboardServer::MacosClipboardServer() {
  m_timer.setInterval(POLL_INTERVAL_MS);
  m_timer.setTimerType(Qt::CoarseTimer);
  connect(&m_timer, &QTimer::timeout, this, &MacosClipboardServer::poll);
}

MacosClipboardServer::~MacosClipboardServer() { endAppNapActivity(); }

QString MacosClipboardServer::id() const { return "macos"; }

bool MacosClipboardServer::isActivatable() const { return QGuiApplication::platformName() == "cocoa"; }

bool MacosClipboardServer::isAlive() const { return m_timer.isActive(); }

bool MacosClipboardServer::start() {
  m_lastChangeCount = currentChangeCount();
  beginAppNapActivity();
  m_timer.start();
  return true;
}

bool MacosClipboardServer::stop() {
  m_timer.stop();
  endAppNapActivity();
  return true;
}

void MacosClipboardServer::beginAppNapActivity() {
  if (m_appNapActivity) return;
  // NSActivityUserInitiated would also prevent idle system sleep
  m_appNapActivity = (__bridge_retained void *)[[NSProcessInfo processInfo]
      beginActivityWithOptions:NSActivityUserInitiatedAllowingIdleSystemSleep
                        reason:@"Clipboard monitoring"];
}

void MacosClipboardServer::endAppNapActivity() {
  if (!m_appNapActivity) return;
  [[NSProcessInfo processInfo] endActivity:(__bridge_transfer NSObject *)m_appNapActivity];
  m_appNapActivity = nullptr;
}

long long MacosClipboardServer::currentChangeCount() const {
  return static_cast<long long>([[NSPasteboard generalPasteboard] changeCount]);
}

MacosClipboardServer::PasteboardInfo MacosClipboardServer::inspectPasteboard() const {
  @autoreleasepool {
    PasteboardInfo info;
    NSPasteboard *pb = [NSPasteboard generalPasteboard];

    for (NSPasteboardItem *item in pb.pasteboardItems) {
      for (NSString *type in item.types) {
        if ([type isEqualToString:CONCEALED_UTI] || [type isEqualToString:TRANSIENT_UTI] ||
            [type isEqualToString:AUTO_GENERATED_UTI]) {
          info.drop = true;
          return info;
        }
      }
      if (!info.sourceApp) {
        NSString *src = [item stringForType:SOURCE_UTI];
        if (src.length > 0) info.sourceApp = QString::fromNSString(src);
      }
    }
    return info;
  }
}

std::optional<QString> MacosClipboardServer::frontmostBundleId() const {
  @autoreleasepool {
    NSRunningApplication *front = [[NSWorkspace sharedWorkspace] frontmostApplication];
    if (!front || front.bundleIdentifier.length == 0) return std::nullopt;
    return QString::fromNSString(front.bundleIdentifier);
  }
}

void MacosClipboardServer::poll() {
  long long const cc = currentChangeCount();
  if (cc == m_lastChangeCount) return;
  m_lastChangeCount = cc;

  auto info = inspectPasteboard();
  if (info.drop) {
    qInfo() << "macOS: dropping concealed/transient/auto-generated selection";
    return;
  }

  auto selection = Clipboard::selectionFromMimeData(QGuiApplication::clipboard()->mimeData());
  if (!selection) return;
  // The pasteboard changed while we were reading it, let the next tick handle it
  if (currentChangeCount() != cc) return;

  selection->sourceApp = info.sourceApp ? info.sourceApp : frontmostBundleId();
  emit selectionAdded(*selection);
}

bool MacosClipboardServer::writeClipboard(QMimeData *data, const Clipboard::CopyOptions &options) {
  bool const ok = AbstractClipboardServer::writeClipboard(data, options);
  if (!ok) return false;

  @autoreleasepool {
    NSPasteboard *pb = [NSPasteboard generalPasteboard];
    auto stamp = [pb](NSString *uti, NSString *value) {
      [pb addTypes:@[ uti ] owner:nil];
      [pb setString:value forType:uti];
    };

    if (options.concealed) stamp(CONCEALED_UTI, @"");
    if (options.transient) stamp(TRANSIENT_UTI, @"");

    NSString *sourceBundleId = options.sourceApp && !options.sourceApp->isEmpty()
                                   ? options.sourceApp->toNSString()
                                   : [[NSBundle mainBundle] bundleIdentifier];
    if (sourceBundleId.length > 0) stamp(SOURCE_UTI, sourceBundleId);
  }
  return ok;
}
