#pragma once
#include "emoji/emoji.hpp"
#include <QDateTime>
#include <qobject.h>
#include <cstdint>
#include <filesystem>
#include <optional>
#include <string>
#include <string_view>
#include <vector>
#include "fuzzy/scored.hpp"

class OmniDatabase;

/**
 * Provides all emoji-related services. User metadata (visit counts, pins and skin tone overrides)
 * is persisted to a simple JSON file under the data directory.
 * The list of emojis is statically generated by a build script and is stored inside `emoji.cpp`.
 */

struct EmojiDataHash {
  size_t operator()(const EmojiData *data) const { return std::hash<std::string_view>()(data->emoji); }
};

struct SerializedEmojiMetadata {
  std::string emoji;
  std::uint32_t visitCount = 0;
  std::optional<std::uint64_t> pinnedAt;
  std::optional<std::uint64_t> lastVisitedAt;
  std::optional<std::string> skinTone;
  std::optional<std::string> keyword;
};

struct EmojiWithMetadata {
  const EmojiData *data = nullptr;
  uint32_t visitCount = 0;
  std::optional<QDateTime> pinnedAt;
  std::optional<emoji::SkinTone> tone;
  std::string keyword; // concatenated as one, space delimited
};

class EmojiService : public QObject {
  Q_OBJECT

signals:
  void pinned(std::string_view emoji) const;
  void unpinned(std::string_view emoji) const;
  void visited(std::string_view emoji) const;
  void rankingReset(std::string_view emoji) const;
  void skintoneChanged(std::string_view emoji) const;
  void keywordsChanged(std::string_view emoji) const;

public:
  using GroupedEmojis = std::vector<std::pair<std::string_view, std::vector<const EmojiData *>>>;

  EmojiService(const std::filesystem::path &path, OmniDatabase *legacyDb = nullptr);

  std::span<Scored<const EmojiData *>> search(std::string_view query) const;

  /**
   * List of emojis, ordered and grouped.
   */
  GroupedEmojis grouped();

  /**
   * Map metadata to the provided list of emojis.
   */
  std::vector<EmojiWithMetadata> mapMetadata(const std::vector<const EmojiData *> &items);
  EmojiWithMetadata mapMetadata(std::string_view emoji);

  std::vector<EmojiWithMetadata> getVisited() const;
  bool pin(std::string_view emoji);
  bool unpin(std::string_view emoji);
  bool registerVisit(std::string_view emoji);
  bool resetRanking(std::string_view emoji);
  bool setSkinTone(std::string_view emoji, emoji::SkinTone tone);
  bool resetSkinTone(std::string_view emoji);
  bool setKeywords(std::string_view emoji, const std::string &text);

private:
  void migrateFromDatabase(OmniDatabase &db);

  SerializedEmojiMetadata const *findEntry(std::string_view emoji) const;
  SerializedEmojiMetadata *findEntry(std::string_view emoji);

  // Return metadata entry for emoji, or create it if it doesn't exist
  SerializedEmojiMetadata &entryFor(std::string_view emoji);

  bool load();
  bool save();

  std::filesystem::path m_path;
  std::vector<SerializedEmojiMetadata> m_entries;
  std::string m_buf;
};
