#pragma once

#include <QGuiApplication>
#include <QObject>
#include <QString>
#include <QDebug>
#include <QTimer>
#include <QVariant>
#include <QJsonObject>
#include <QJsonArray>
#include <QJsonValue>
#include <QJsonDocument>
#include <QUrl>
#include <QColor>
#include <QtConcurrent/QtConcurrent>
#include <QDBusConnection>
#include <QDBusInterface>
#include <QEvent>
#include <QSqlQuery>
#include <QFutureWatcher>

#include <memory>
#include <vector>
#include <optional>
#include <variant>
#include <unordered_map>
#include <filesystem>
#include <ranges>
#include <string>
