function(embed_file TARGET FILE_PATH VAR_NAME)
    file(READ "${FILE_PATH}" EMBED_FILE_CONTENT)
    set(EMBED_VAR_NAME "${VAR_NAME}")
    set(OUTPUT_FILE "${CMAKE_CURRENT_BINARY_DIR}/generated/${VAR_NAME}.hpp")
    configure_file("${CMAKE_SOURCE_DIR}/cmake/embed.hpp.in" "${OUTPUT_FILE}" @ONLY NEWLINE_STYLE LF)
    target_sources(${TARGET} PRIVATE "${OUTPUT_FILE}")
    target_include_directories(${TARGET} PRIVATE "${CMAKE_CURRENT_BINARY_DIR}/generated")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${FILE_PATH}")
endfunction()
