function(link_swift_runtime target)
	execute_process(
		COMMAND ${CMAKE_Swift_COMPILER} -print-target-info
		OUTPUT_VARIABLE info OUTPUT_STRIP_TRAILING_WHITESPACE)
	string(JSON paths GET "${info}" paths runtimeLibraryPaths)
	string(JSON count LENGTH "${paths}")
	if (count EQUAL 0)
		return()
	endif()
	math(EXPR last "${count} - 1")
	foreach(i RANGE ${last})
		string(JSON path GET "${paths}" ${i})
		target_link_options(${target} INTERFACE "-L${path}" "LINKER:SHELL:-rpath ${path}")
	endforeach()
endfunction()
