name: Build AppImage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.target.runner }}
    container: registry.depot.dev/dwd5s9sq7d:${{ matrix.target.tag }}

    strategy:
      fail-fast: false
      matrix:
        target:
          - arch: amd64
            runner: depot-ubuntu-24.04-16
            tag: appimage-amd64-latest
          - arch: arm64
            runner: depot-ubuntu-24.04-arm-16
            tag: appimage-arm64-latest

    name: Build AppImage (${{ matrix.target.arch }})

    env:
      INSTALL_DIR: ${{ github.workspace }}/install
      APPIMAGE_EXTRACT_AND_RUN: "1"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: appimage-${{ matrix.target.arch }}
          max-size: 0

      - name: Configure CMake
        run: |
          cmake -S . -B build -G Ninja              \
          -DCMAKE_BUILD_TYPE=Release                \
          -DCMAKE_INSTALL_PREFIX="${INSTALL_DIR}"

      - name: Build
        run: cmake --build build --parallel $(nproc)

      - name: Install
        run: cmake --install build

      - name: Make AppImage
        run: |
          chmod +x ./scripts/mkappimage.sh
          ./scripts/mkappimage.sh "${INSTALL_DIR}" AppDir

