name: "Push to Cachix"
on:
  push:
    branches:
      - main

jobs:
  push_to_cachix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [depot-ubuntu-24.04-16, depot-ubuntu-24.04-arm-16, depot-macos-26]
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
    - name: Cache Nix Evaluation
      uses: actions/cache@v4
      with:
        path: ~/.cache/nix
        key: nix-eval-${{ hashFiles('flake.lock') }}
    - uses: cachix/cachix-action@v14
      with:
        name: vicinae
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Build Flake
      run: nix build -L
    - name: Run Test Shell
      run: nix develop --command echo OK
